-- =============================================================================
-- Nocturne Pipeline: Step 12 - Target-Scoped L3 Knowledge Graph
-- =============================================================================
-- Only accepted, grounded elements belonging to an L2 target_confirmed graph
-- component enter L3. A document containing target and non-target leaks promotes
-- only the claim connected to the monitored organization and its local context.
--
-- Corroboration counts DISTINCT CONTENT_SHA256. Mirrors with the same content
-- remain observable as repeat sightings but never increase corroboration.
-- Organization-subject grouping remains a documented hackathon simplification.
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE SCHEMA NOCTURNE.RAW;

-- The ownership edge is the L3 boundary. It supplies the exact target-connected
-- claim and a stable monitored-organization node even when the model extracted
-- a configured domain instead of the canonical organization name.
CREATE OR REPLACE DYNAMIC TABLE NOCTURNE.RAW.DT_L3_TARGET_CLAIMS
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = DOWNSTREAM
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
  SELECT
    EDGE.ORG_ID,
    EDGE.DOC_ID,
    EDGE.DEDUPE_KEY,
    EDGE.SOURCE_KEY AS CLAIM_KEY,
    MIN(EDGE.TARGET_RESOLVED_ORG_NODE_KEY) AS SUBJECT_NODE_KEY,
    PAGE.CONTENT_SHA256,
    PAGE._SOURCE_FILE AS SOURCE_FILE,
    PAGE.TITLE,
    PAGE.URL,
    PAGE.FETCHED_AT,
    'target_incident' AS GRAPH_SCOPE
  FROM NOCTURNE.RAW.DT_L2_EDGES AS EDGE
  INNER JOIN NOCTURNE.RAW.DT_PAGE_CLASSIFICATION AS PAGE
    ON PAGE.ORG_ID = EDGE.ORG_ID
    AND PAGE.DEDUPE_KEY = EDGE.DEDUPE_KEY
  WHERE EDGE.IS_ACCEPTED
    AND EDGE.IS_GROUNDED
    AND EDGE.EDGE_TYPE = 'ALLEGEDLY_AFFECTS'
    AND EDGE.SOURCE_KIND = 'claim'
    AND EDGE.TARGET_TYPE IN ('organization', 'domain')
    AND EDGE.TARGET_IS_MONITORED_ORG
    AND EDGE.TARGET_RESOLVED_ORG_NODE_KEY IS NOT NULL
    AND PAGE.L2_ROUTE = 'target_confirmed'
    AND PAGE.L3_ELIGIBLE
    AND PAGE.TARGET_ALERT_ELIGIBLE
  GROUP BY
    EDGE.ORG_ID,
    EDGE.DOC_ID,
    EDGE.DEDUPE_KEY,
    EDGE.SOURCE_KEY,
    PAGE.CONTENT_SHA256,
    PAGE._SOURCE_FILE,
    PAGE.TITLE,
    PAGE.URL,
    PAGE.FETCHED_AT;

-- Promote the target claim's direct edges plus marketplace/contact context for
-- an actor connected to that target claim. Unrelated claims from the same page
-- and their graph components are excluded.
CREATE OR REPLACE DYNAMIC TABLE NOCTURNE.RAW.DT_L3_PROMOTED_EDGES
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = DOWNSTREAM
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
  WITH ELIGIBLE_EDGES AS (
    SELECT
      EDGE.*,
      TARGET_CLAIM.CLAIM_KEY AS TARGET_CLAIM_KEY,
      TARGET_CLAIM.CONTENT_SHA256,
      TARGET_CLAIM.SOURCE_FILE,
      TARGET_CLAIM.GRAPH_SCOPE
    FROM NOCTURNE.RAW.DT_L2_EDGES AS EDGE
    INNER JOIN NOCTURNE.RAW.DT_L3_TARGET_CLAIMS AS TARGET_CLAIM
      ON TARGET_CLAIM.ORG_ID = EDGE.ORG_ID
      AND TARGET_CLAIM.DEDUPE_KEY = EDGE.DEDUPE_KEY
    WHERE EDGE.IS_ACCEPTED
      AND EDGE.IS_GROUNDED
  ),
  DIRECT_EDGES AS (
    SELECT *
    FROM ELIGIBLE_EDGES
    WHERE SOURCE_KEY = TARGET_CLAIM_KEY
      OR TARGET_KEY = TARGET_CLAIM_KEY
  ),
  CONNECTED_ACTORS AS (
    SELECT DISTINCT
      ORG_ID,
      DEDUPE_KEY,
      CASE
        WHEN SOURCE_TYPE = 'actor_alias' THEN SOURCE_KEY
        WHEN TARGET_TYPE = 'actor_alias' THEN TARGET_KEY
      END AS ACTOR_NODE_KEY
    FROM DIRECT_EDGES
    WHERE SOURCE_TYPE = 'actor_alias'
      OR TARGET_TYPE = 'actor_alias'
  ),
  ACTOR_CONTEXT_EDGES AS (
    SELECT EDGE.*
    FROM ELIGIBLE_EDGES AS EDGE
    INNER JOIN CONNECTED_ACTORS AS ACTOR
      ON ACTOR.ORG_ID = EDGE.ORG_ID
      AND ACTOR.DEDUPE_KEY = EDGE.DEDUPE_KEY
      AND EDGE.SOURCE_KEY = ACTOR.ACTOR_NODE_KEY
    WHERE EDGE.EDGE_TYPE IN ('LISTED_ON', 'CONTACTED_VIA')
  ),
  COMBINED AS (
    SELECT * FROM DIRECT_EDGES
    UNION ALL
    SELECT * FROM ACTOR_CONTEXT_EDGES
  )
  SELECT *
  FROM COMBINED
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY ORG_ID, DEDUPE_KEY, EDGE_KEY
    ORDER BY EDGE_KEY
  ) = 1;

-- Nodes consist only of accepted entity endpoints in the promoted component,
-- plus a canonical target node synthesized from configuration for domain-only
-- ownership evidence.
CREATE OR REPLACE DYNAMIC TABLE NOCTURNE.RAW.DIM_GRAPH_NODE
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = DOWNSTREAM
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
  WITH ENDPOINT_KEYS AS (
    SELECT
      ORG_ID,
      DEDUPE_KEY,
      CONTENT_SHA256,
      SOURCE_KEY AS NODE_KEY
    FROM NOCTURNE.RAW.DT_L3_PROMOTED_EDGES
    WHERE SOURCE_KIND = 'entity'
    UNION
    SELECT
      ORG_ID,
      DEDUPE_KEY,
      CONTENT_SHA256,
      TARGET_KEY
    FROM NOCTURNE.RAW.DT_L3_PROMOTED_EDGES
    WHERE TARGET_KIND = 'entity'
  ),
  ENTITY_MENTIONS AS (
    SELECT DISTINCT
      ENTITY.ORG_ID,
      ENTITY.DEDUPE_KEY,
      ENDPOINT.CONTENT_SHA256,
      ENTITY.NODE_KEY,
      ENTITY.ENTITY_TYPE AS NODE_TYPE,
      ENTITY.NORMALIZED_NAME,
      ENTITY.ENTITY_NAME AS DISPLAY_NAME,
      ENTITY.IS_MONITORED_ORG,
      ENTITY.FETCHED_AT
    FROM ENDPOINT_KEYS AS ENDPOINT
    INNER JOIN NOCTURNE.RAW.DT_L2_ENTITIES AS ENTITY
      ON ENTITY.ORG_ID = ENDPOINT.ORG_ID
      AND ENTITY.DEDUPE_KEY = ENDPOINT.DEDUPE_KEY
      AND ENTITY.NODE_KEY = ENDPOINT.NODE_KEY
    WHERE ENTITY.IS_ACCEPTED
      AND ENTITY.IS_GROUNDED
  ),
  CANONICAL_TARGET_MENTIONS AS (
    SELECT DISTINCT
      CLAIM.ORG_ID,
      CLAIM.DEDUPE_KEY,
      CLAIM.CONTENT_SHA256,
      CLAIM.SUBJECT_NODE_KEY AS NODE_KEY,
      'organization' AS NODE_TYPE,
      NOCTURNE.RAW.NORMALIZE_ENTITY_NAME(ORGANIZATION.CANONICAL_NAME)
        AS NORMALIZED_NAME,
      ORGANIZATION.CANONICAL_NAME AS DISPLAY_NAME,
      TRUE AS IS_MONITORED_ORG,
      CLAIM.FETCHED_AT
    FROM NOCTURNE.RAW.DT_L3_TARGET_CLAIMS AS CLAIM
    INNER JOIN NOCTURNE.CONFIG.MONITORED_ORGANIZATIONS AS ORGANIZATION
      ON ORGANIZATION.ORG_ID = CLAIM.ORG_ID
      AND ORGANIZATION.ENABLED = TRUE
  ),
  MENTIONS AS (
    SELECT * FROM ENTITY_MENTIONS
    UNION ALL
    SELECT * FROM CANONICAL_TARGET_MENTIONS
  )
  SELECT
    ORG_ID,
    NODE_KEY,
    NODE_TYPE,
    NORMALIZED_NAME,
    MODE(DISPLAY_NAME) AS DISPLAY_NAME,
    COUNT(*) AS MENTION_COUNT,
    COUNT(DISTINCT DEDUPE_KEY) AS SIGHTING_COUNT,
    COUNT(DISTINCT CONTENT_SHA256) AS DOC_COUNT,
    GREATEST(
      0,
      COUNT(DISTINCT DEDUPE_KEY) - COUNT(DISTINCT CONTENT_SHA256)
    ) AS MIRROR_SIGHTING_COUNT,
    BOOLOR_AGG(IS_MONITORED_ORG) AS IS_MONITORED_ORG,
    MIN(FETCHED_AT) AS FIRST_SEEN,
    MAX(FETCHED_AT) AS LAST_SEEN,
    'target_incident' AS GRAPH_SCOPE
  FROM MENTIONS
  GROUP BY ORG_ID, NODE_KEY, NODE_TYPE, NORMALIZED_NAME;

CREATE OR REPLACE DYNAMIC TABLE NOCTURNE.RAW.FCT_GRAPH_EDGE
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = DOWNSTREAM
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
  SELECT
    ORG_ID,
    SHA2(ORG_ID || '|' || SOURCE_KEY || '|' || EDGE_TYPE || '|' || TARGET_KEY)
      AS GRAPH_EDGE_KEY,
    SOURCE_KEY,
    EDGE_TYPE,
    TARGET_KEY,
    MODE(SOURCE_KIND) AS SOURCE_KIND,
    MODE(SOURCE_TYPE) AS SOURCE_TYPE,
    MODE(TARGET_KIND) AS TARGET_KIND,
    MODE(TARGET_TYPE) AS TARGET_TYPE,
    COUNT(*) AS MENTION_COUNT,
    COUNT(DISTINCT DEDUPE_KEY) AS SIGHTING_COUNT,
    COUNT(DISTINCT CONTENT_SHA256) AS DOC_COUNT,
    GREATEST(
      0,
      COUNT(DISTINCT DEDUPE_KEY) - COUNT(DISTINCT CONTENT_SHA256)
    ) AS MIRROR_SIGHTING_COUNT,
    MAX(EVIDENCE_TEXT) AS SAMPLE_EVIDENCE_TEXT,
    MIN(FETCHED_AT) AS FIRST_SEEN,
    MAX(FETCHED_AT) AS LAST_SEEN,
    'target_incident' AS GRAPH_SCOPE
  FROM NOCTURNE.RAW.DT_L3_PROMOTED_EDGES
  GROUP BY ORG_ID, SOURCE_KEY, EDGE_TYPE, TARGET_KEY;

-- Corroboration deliberately remains simple for the hackathon: independent
-- content items affecting the same monitored organization corroborate one
-- another. Claim category and event-time clustering are future refinements.
CREATE OR REPLACE DYNAMIC TABLE NOCTURNE.RAW.DT_L3_CLAIM_CORROBORATION
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = DOWNSTREAM
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
  WITH TARGET_CLAIM_ROWS AS (
    SELECT
      TARGET.ORG_ID,
      TARGET.DOC_ID,
      TARGET.DEDUPE_KEY,
      TARGET.CONTENT_SHA256,
      TARGET.SOURCE_FILE,
      TARGET.SUBJECT_NODE_KEY,
      TARGET.GRAPH_SCOPE,
      CLAIM.CLAIM_KEY,
      CLAIM.STATEMENT,
      CLAIM.CLAIM_STATUS_EXTRACTED,
      CLAIM.QUANTITY_CLAIMED,
      CLAIM.EVIDENCE_TEXT,
      CLAIM.EVIDENCE_START,
      CLAIM.EVIDENCE_END,
      CLAIM.GROUNDING_LEVEL,
      CLAIM.SELECTED_WINDOW_ID,
      CLAIM.FETCHED_AT
    FROM NOCTURNE.RAW.DT_L3_TARGET_CLAIMS AS TARGET
    INNER JOIN NOCTURNE.RAW.DT_L2_CLAIMS AS CLAIM
      ON CLAIM.ORG_ID = TARGET.ORG_ID
      AND CLAIM.DEDUPE_KEY = TARGET.DEDUPE_KEY
      AND CLAIM.CLAIM_KEY = TARGET.CLAIM_KEY
    WHERE CLAIM.IS_ACCEPTED
      AND CLAIM.IS_GROUNDED
  ),
  ORG_TOTALS AS (
    SELECT
      ORG_ID,
      COUNT(DISTINCT CONTENT_SHA256) AS CORROBORATION_COUNT,
      COUNT(DISTINCT DEDUPE_KEY) AS SIGHTING_COUNT,
      COUNT(DISTINCT CLAIM_KEY) AS UNIQUE_CLAIM_COUNT,
      COUNT(DISTINCT IFF(
        CLAIM_STATUS_EXTRACTED = 'disputed',
        CONTENT_SHA256,
        NULL
      )) AS DISPUTE_COUNT
    FROM TARGET_CLAIM_ROWS
    GROUP BY ORG_ID
  )
  SELECT
    CLAIM.ORG_ID,
    CLAIM.DOC_ID,
    CLAIM.DEDUPE_KEY,
    CLAIM.CONTENT_SHA256,
    CLAIM.SOURCE_FILE,
    CLAIM.CLAIM_KEY,
    CLAIM.STATEMENT,
    CLAIM.CLAIM_STATUS_EXTRACTED,
    CLAIM.QUANTITY_CLAIMED,
    TRUE AS IS_GROUNDED,
    TRUE AS IS_ACCEPTED,
    CLAIM.GROUNDING_LEVEL,
    CLAIM.EVIDENCE_TEXT,
    CLAIM.EVIDENCE_START,
    CLAIM.EVIDENCE_END,
    CLAIM.SELECTED_WINDOW_ID,
    CLAIM.SUBJECT_NODE_KEY,
    ORGANIZATION.CANONICAL_NAME AS SUBJECT_NAME,
    'organization' AS SUBJECT_TYPE,
    TRUE AS SUBJECT_IS_MONITORED_ORG,
    TOTALS.CORROBORATION_COUNT,
    TOTALS.SIGHTING_COUNT,
    GREATEST(
      0,
      TOTALS.SIGHTING_COUNT - TOTALS.CORROBORATION_COUNT
    ) AS MIRROR_SIGHTING_COUNT,
    TOTALS.UNIQUE_CLAIM_COUNT,
    TOTALS.DISPUTE_COUNT,
    CASE
      WHEN TOTALS.DISPUTE_COUNT > 0 THEN 'disputed'
      WHEN TOTALS.CORROBORATION_COUNT >= 3 THEN 'corroborated'
      WHEN TOTALS.CORROBORATION_COUNT = 2 THEN 'partially_corroborated'
      WHEN CLAIM.CLAIM_STATUS_EXTRACTED = 'self_evidenced'
        THEN 'self_evidenced'
      ELSE 'unverified'
    END AS CLAIM_STATUS,
    CLAIM.GRAPH_SCOPE,
    'organization_subject_content_hash_v2' AS CORROBORATION_METHOD_VERSION
  FROM TARGET_CLAIM_ROWS AS CLAIM
  INNER JOIN ORG_TOTALS AS TOTALS
    ON TOTALS.ORG_ID = CLAIM.ORG_ID
  INNER JOIN NOCTURNE.CONFIG.MONITORED_ORGANIZATIONS AS ORGANIZATION
    ON ORGANIZATION.ORG_ID = CLAIM.ORG_ID
    AND ORGANIZATION.ENABLED = TRUE;

CREATE OR REPLACE DYNAMIC TABLE NOCTURNE.RAW.DT_L3_ACTOR_CREDIBILITY
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = DOWNSTREAM
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
  WITH CLAIM_AUTHOR AS (
    SELECT
      EDGE.ORG_ID,
      EDGE.DEDUPE_KEY,
      EDGE.CONTENT_SHA256,
      EDGE.SOURCE_KEY AS ACTOR_NODE_KEY,
      EDGE.TARGET_KEY AS CLAIM_KEY
    FROM NOCTURNE.RAW.DT_L3_PROMOTED_EDGES AS EDGE
    WHERE EDGE.EDGE_TYPE = 'MADE_CLAIM'
      AND EDGE.SOURCE_TYPE = 'actor_alias'
      AND EDGE.TARGET_KIND = 'claim'
  ),
  ACTOR_VENUES AS (
    SELECT
      ORG_ID,
      SOURCE_KEY AS ACTOR_NODE_KEY,
      COUNT(DISTINCT TARGET_KEY) AS MARKETPLACE_COUNT
    FROM NOCTURNE.RAW.DT_L3_PROMOTED_EDGES
    WHERE EDGE_TYPE = 'LISTED_ON'
      AND SOURCE_TYPE = 'actor_alias'
      AND TARGET_TYPE = 'marketplace'
    GROUP BY ORG_ID, SOURCE_KEY
  ),
  ACTOR_CLAIMS AS (
    SELECT
      AUTHOR.ORG_ID,
      AUTHOR.ACTOR_NODE_KEY,
      COUNT(DISTINCT AUTHOR.CLAIM_KEY) AS TOTAL_CLAIM_COUNT,
      COUNT(DISTINCT AUTHOR.CONTENT_SHA256) AS DOC_COUNT,
      COUNT(DISTINCT AUTHOR.DEDUPE_KEY) AS SIGHTING_COUNT,
      COUNT(DISTINCT IFF(
        CORROBORATION.CORROBORATION_COUNT >= 2
          AND CORROBORATION.DISPUTE_COUNT = 0,
        AUTHOR.CLAIM_KEY,
        NULL
      )) AS CORROBORATED_CLAIM_COUNT,
      COUNT(DISTINCT IFF(
        CORROBORATION.DISPUTE_COUNT > 0,
        AUTHOR.CLAIM_KEY,
        NULL
      )) AS DISPUTED_CLAIM_COUNT
    FROM CLAIM_AUTHOR AS AUTHOR
    LEFT JOIN NOCTURNE.RAW.DT_L3_CLAIM_CORROBORATION AS CORROBORATION
      ON CORROBORATION.ORG_ID = AUTHOR.ORG_ID
      AND CORROBORATION.CLAIM_KEY = AUTHOR.CLAIM_KEY
    GROUP BY AUTHOR.ORG_ID, AUTHOR.ACTOR_NODE_KEY
  )
  SELECT
    CLAIMS.ORG_ID,
    CLAIMS.ACTOR_NODE_KEY,
    NODE.DISPLAY_NAME AS ACTOR_NAME,
    CLAIMS.TOTAL_CLAIM_COUNT,
    CLAIMS.CORROBORATED_CLAIM_COUNT,
    CLAIMS.DISPUTED_CLAIM_COUNT,
    CLAIMS.DOC_COUNT,
    CLAIMS.SIGHTING_COUNT,
    GREATEST(0, CLAIMS.SIGHTING_COUNT - CLAIMS.DOC_COUNT)
      AS MIRROR_SIGHTING_COUNT,
    COALESCE(VENUES.MARKETPLACE_COUNT, 0) AS MARKETPLACE_COUNT,
    NODE.FIRST_SEEN,
    NODE.LAST_SEEN,
    GREATEST(0, LEAST(100,
        40 * LEAST(1.0, CLAIMS.CORROBORATED_CLAIM_COUNT / 3.0)
      + 25 * LEAST(1.0, COALESCE(VENUES.MARKETPLACE_COUNT, 0) / 3.0)
      + 20 * LEAST(1.0, CLAIMS.DOC_COUNT / 3.0)
      + 15
      - 20 * LEAST(1.0, CLAIMS.DISPUTED_CLAIM_COUNT / 2.0)
    )) AS ACTOR_CREDIBILITY_SCORE,
    'target_scoped_actor_credibility_v2' AS ACTOR_METHOD_VERSION,
    'target_incident' AS GRAPH_SCOPE
  FROM ACTOR_CLAIMS AS CLAIMS
  LEFT JOIN ACTOR_VENUES AS VENUES
    ON VENUES.ORG_ID = CLAIMS.ORG_ID
    AND VENUES.ACTOR_NODE_KEY = CLAIMS.ACTOR_NODE_KEY
  LEFT JOIN NOCTURNE.RAW.DIM_GRAPH_NODE AS NODE
    ON NODE.ORG_ID = CLAIMS.ORG_ID
    AND NODE.NODE_KEY = CLAIMS.ACTOR_NODE_KEY;

CREATE OR REPLACE DYNAMIC TABLE NOCTURNE.RAW.DT_L3_ACTOR_ORG_PATHS
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = DOWNSTREAM
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
  SELECT
    EDGE.ORG_ID,
    EDGE.DOC_ID,
    EDGE.DEDUPE_KEY,
    EDGE.CONTENT_SHA256,
    EDGE.SOURCE_KEY AS ACTOR_NODE_KEY,
    ACTOR_NODE.DISPLAY_NAME AS ACTOR_NAME,
    CLAIM.CLAIM_KEY,
    CLAIM.STATEMENT,
    CLAIM.CLAIM_STATUS,
    CLAIM.CORROBORATION_COUNT,
    CLAIM.SUBJECT_NODE_KEY AS ORG_NODE_KEY,
    CLAIM.SUBJECT_NAME AS ORG_NAME,
    TRUE AS SUBJECT_IS_MONITORED_ORG,
    COALESCE(ACTOR.ACTOR_CREDIBILITY_SCORE, 0) AS ACTOR_CREDIBILITY_SCORE,
    'target_incident' AS GRAPH_SCOPE
  FROM NOCTURNE.RAW.DT_L3_PROMOTED_EDGES AS EDGE
  INNER JOIN NOCTURNE.RAW.DT_L3_CLAIM_CORROBORATION AS CLAIM
    ON CLAIM.ORG_ID = EDGE.ORG_ID
    AND CLAIM.CLAIM_KEY = EDGE.TARGET_KEY
  LEFT JOIN NOCTURNE.RAW.DIM_GRAPH_NODE AS ACTOR_NODE
    ON ACTOR_NODE.ORG_ID = EDGE.ORG_ID
    AND ACTOR_NODE.NODE_KEY = EDGE.SOURCE_KEY
  LEFT JOIN NOCTURNE.RAW.DT_L3_ACTOR_CREDIBILITY AS ACTOR
    ON ACTOR.ORG_ID = EDGE.ORG_ID
    AND ACTOR.ACTOR_NODE_KEY = EDGE.SOURCE_KEY
  WHERE EDGE.EDGE_TYPE = 'MADE_CLAIM'
    AND EDGE.SOURCE_TYPE = 'actor_alias'
    AND EDGE.TARGET_KIND = 'claim';

-- Safe checks: no raw page text or exact indicator value is selected.
-- SELECT ORG_ID, COUNT(*) AS TARGET_CLAIMS,
--   COUNT(DISTINCT CONTENT_SHA256) AS INDEPENDENT_CONTENT,
--   COUNT(DISTINCT DEDUPE_KEY) AS SIGHTINGS
-- FROM NOCTURNE.RAW.DT_L3_TARGET_CLAIMS GROUP BY ORG_ID;
--
-- SELECT ORG_ID, GRAPH_SCOPE, NODE_TYPE, COUNT(*) AS NODES
-- FROM NOCTURNE.RAW.DIM_GRAPH_NODE
-- GROUP BY ORG_ID, GRAPH_SCOPE, NODE_TYPE;
