-- =============================================================================
-- Nocturne Pipeline: Step 13 - Target Impact, Confidence, and Triage Priority
-- =============================================================================
-- L1 labels cannot create a target score. Metrics exist only after L2 accepted
-- a grounded target ownership edge and leak-type AI succeeded.
--
-- The model deliberately separates three different questions:
--   IMPACT SEVERITY:     How harmful is the alleged disclosure if true?
--   EVIDENCE CONFIDENCE: How strongly is that allegation supported?
--   TRIAGE PRIORITY:     In what order should an analyst investigate it?
--
-- None of these scores is a probability. Impact and confidence are never
-- multiplied. Every input component is retained for explanation and tuning.
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE SCHEMA NOCTURNE.RAW;

CREATE OR REPLACE DYNAMIC TABLE NOCTURNE.RAW.DT_L4_DOCUMENT_SEVERITY
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '5 MINUTE'
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
  WITH DOC_CLAIM_STATS AS (
    SELECT
      ORG_ID,
      DOC_ID,
      DEDUPE_KEY,
      COUNT(DISTINCT CLAIM_KEY) AS L3_CLAIM_COUNT,
      COUNT_IF(GROUNDING_LEVEL = 'exact') AS EXACT_GROUNDED_CLAIM_COUNT,
      COUNT_IF(GROUNDING_LEVEL = 'normalized')
        AS NORMALIZED_GROUNDED_CLAIM_COUNT,
      MAX(CORROBORATION_COUNT) AS CORROBORATION_COUNT,
      MAX(SIGHTING_COUNT) AS SIGHTING_COUNT,
      MAX(MIRROR_SIGHTING_COUNT) AS MIRROR_SIGHTING_COUNT,
      MAX(DISPUTE_COUNT) AS DISPUTE_COUNT,
      MAX(QUANTITY_CLAIMED) AS MAX_QUANTITY_CLAIMED,
      ARRAY_AGG(DISTINCT CLAIM_STATUS) AS CLAIM_STATUSES,
      ARRAY_AGG(DISTINCT CLAIM_STATUS_EXTRACTED)
        AS CLAIM_STATUSES_EXTRACTED
    FROM NOCTURNE.RAW.DT_L3_CLAIM_CORROBORATION
    WHERE IS_ACCEPTED
      AND IS_GROUNDED
      AND GRAPH_SCOPE = 'target_incident'
    GROUP BY ORG_ID, DOC_ID, DEDUPE_KEY
  ),
  DOC_ACTOR AS (
    SELECT
      ORG_ID,
      DOC_ID,
      DEDUPE_KEY,
      MAX(ACTOR_CREDIBILITY_SCORE) AS ACTOR_CREDIBILITY_SCORE,
      MAX_BY(ACTOR_NODE_KEY, ACTOR_CREDIBILITY_SCORE) AS ACTOR_NODE_KEY,
      MAX_BY(ACTOR_NAME, ACTOR_CREDIBILITY_SCORE) AS ACTOR_NAME
    FROM NOCTURNE.RAW.DT_L3_ACTOR_ORG_PATHS
    WHERE GRAPH_SCOPE = 'target_incident'
    GROUP BY ORG_ID, DOC_ID, DEDUPE_KEY
  ),
  BASE AS (
    SELECT
      PAGE.* EXCLUDE (
        IMPACT_SCORE,
        TARGET_RELEVANCE_SCORE,
        PRELIMINARY_SEVERITY_SCORE,
        PRELIMINARY_SEVERITY_BAND,
        SCORE_METHOD_VERSION
      ),
      COALESCE(CLAIM.L3_CLAIM_COUNT, 0) AS L3_CLAIM_COUNT,
      COALESCE(CLAIM.EXACT_GROUNDED_CLAIM_COUNT, 0)
        AS EXACT_GROUNDED_CLAIM_COUNT,
      COALESCE(CLAIM.NORMALIZED_GROUNDED_CLAIM_COUNT, 0)
        AS NORMALIZED_GROUNDED_CLAIM_COUNT,
      COALESCE(CLAIM.CORROBORATION_COUNT, 1) AS CORROBORATION_COUNT,
      COALESCE(CLAIM.SIGHTING_COUNT, 1) AS GRAPH_SIGHTING_COUNT,
      COALESCE(CLAIM.MIRROR_SIGHTING_COUNT, 0)
        AS MIRROR_SIGHTING_COUNT,
      COALESCE(CLAIM.DISPUTE_COUNT, 0) AS DISPUTE_COUNT,
      CLAIM.MAX_QUANTITY_CLAIMED,
      CLAIM.CLAIM_STATUSES,
      CLAIM.CLAIM_STATUSES_EXTRACTED,
      COALESCE(ACTOR.ACTOR_CREDIBILITY_SCORE, 0)
        AS ACTOR_CREDIBILITY_SCORE,
      ACTOR.ACTOR_NODE_KEY,
      ACTOR.ACTOR_NAME,
      COALESCE(
        ARRAY_CONTAINS('credential'::VARIANT, PAGE.LEAK_TYPE_LABELS),
        FALSE
      ) AS HAS_CREDENTIAL_LEAK,
      COALESCE(
        ARRAY_CONTAINS('corporate_data'::VARIANT, PAGE.LEAK_TYPE_LABELS),
        FALSE
      ) AS HAS_CORPORATE_DATA_LEAK,
      COALESCE(
        ARRAY_CONTAINS('pii'::VARIANT, PAGE.LEAK_TYPE_LABELS),
        FALSE
      ) AS HAS_PII_LEAK,
      COALESCE(
        ARRAY_CONTAINS('financial'::VARIANT, PAGE.LEAK_TYPE_LABELS),
        FALSE
      ) AS HAS_FINANCIAL_LEAK,
      COALESCE(
        ARRAY_CONTAINS('malware_exploit'::VARIANT, PAGE.LEAK_TYPE_LABELS),
        FALSE
      ) AS HAS_MALWARE_EXPLOIT_LEAK,
      COALESCE(
        PAGE.TARGET_ALERT_ELIGIBLE
          AND PAGE.L2_ROUTE = 'target_confirmed'
          AND PAGE.GRAPH_SCOPE = 'target_incident'
          AND PAGE.TARGET_LEAK_RELATION_GROUNDED
          AND PAGE.LEAK_TYPE_AI_STATUS = 'success'
          AND PAGE.ENTITY_LINK_CONFIDENCE IS NOT NULL
          AND COALESCE(CLAIM.L3_CLAIM_COUNT, 0) > 0
          AND PAGE.CONTENT_SHA256 IS NOT NULL,
        FALSE
      ) AS TARGET_SCORE_ELIGIBLE
    FROM NOCTURNE.RAW.DT_PAGE_CLASSIFICATION AS PAGE
    LEFT JOIN DOC_CLAIM_STATS AS CLAIM
      ON CLAIM.ORG_ID = PAGE.ORG_ID
      AND CLAIM.DEDUPE_KEY = PAGE.DEDUPE_KEY
    LEFT JOIN DOC_ACTOR AS ACTOR
      ON ACTOR.ORG_ID = PAGE.ORG_ID
      AND ACTOR.DEDUPE_KEY = PAGE.DEDUPE_KEY
  ),
  TYPE_COMPONENTS AS (
    SELECT
      *,
      IFF(HAS_CREDENTIAL_LEAK, 1, 0)
        + IFF(HAS_CORPORATE_DATA_LEAK, 1, 0)
        + IFF(HAS_PII_LEAK, 1, 0)
        + IFF(HAS_FINANCIAL_LEAK, 1, 0)
        + IFF(HAS_MALWARE_EXPLOIT_LEAK, 1, 0)
        AS LEAK_TYPE_COUNT,
      GREATEST(
        IFF(HAS_FINANCIAL_LEAK, 90, 0),
        IFF(HAS_CREDENTIAL_LEAK, 85, 0),
        IFF(HAS_PII_LEAK, 80, 0),
        IFF(HAS_CORPORATE_DATA_LEAK, 70, 0),
        IFF(HAS_MALWARE_EXPLOIT_LEAK, 70, 0)
      ) AS MAX_TYPE_SENSITIVITY_SCORE
    FROM BASE
  ),
  IMPACT_COMPONENTS AS (
    SELECT
      *,
      CASE WHEN TARGET_SCORE_ELIGIBLE
        THEN LEAST(
          100,
          MAX_TYPE_SENSITIVITY_SCORE
            + 3 * GREATEST(0, LEAK_TYPE_COUNT - 1)
        )
      END AS DATA_SENSITIVITY_SCORE,
      CASE
        WHEN NOT TARGET_SCORE_ELIGIBLE THEN NULL
        WHEN COALESCE(
          ARRAY_CONTAINS(
            'self_evidenced'::VARIANT,
            CLAIM_STATUSES_EXTRACTED
          ),
          FALSE
        ) THEN 100
        WHEN COALESCE(STRONG_INDICATOR_COUNT, 0) > 0 THEN 90
        WHEN HAS_CREDENTIAL_LEAK OR HAS_FINANCIAL_LEAK THEN 75
        ELSE 60
      END AS EXPOSURE_ACTIONABILITY_SCORE,
      CASE
        WHEN NOT TARGET_SCORE_ELIGIBLE
          OR MAX_QUANTITY_CLAIMED IS NULL THEN NULL
        ELSE LEAST(
          100,
          100 * LOG(10, 1 + GREATEST(0, MAX_QUANTITY_CLAIMED))
            / LOG(10, 10000001)
        )
      END AS RECORD_SCALE_SCORE,
      CASE
        WHEN NOT TARGET_SCORE_ELIGIBLE THEN NULL
        ELSE COALESCE(ENTITY_LINK_CONFIDENCE, 0)
      END AS OWNERSHIP_EVIDENCE_SCORE,
      CASE
        WHEN NOT TARGET_SCORE_ELIGIBLE THEN NULL
        WHEN EXACT_GROUNDED_CLAIM_COUNT > 0 THEN 100
        WHEN NORMALIZED_GROUNDED_CLAIM_COUNT > 0 THEN 85
        ELSE 70
      END AS GROUNDING_CONFIDENCE_SCORE,
      CASE
        WHEN NOT TARGET_SCORE_ELIGIBLE THEN NULL
        WHEN DISPUTE_COUNT > 0 THEN 20
        WHEN COALESCE(
          ARRAY_CONTAINS(
            'self_evidenced'::VARIANT,
            CLAIM_STATUSES_EXTRACTED
          ),
          FALSE
        ) THEN 95
        WHEN COALESCE(STRONG_INDICATOR_COUNT, 0) > 0 THEN 80
        ELSE 50
      END AS CLAIM_PROOF_SCORE,
      CASE
        WHEN NOT TARGET_SCORE_ELIGIBLE THEN NULL
        WHEN DISPUTE_COUNT > 0 THEN 20
        WHEN CORROBORATION_COUNT >= 5 THEN 95
        WHEN CORROBORATION_COUNT >= 3 THEN 85
        WHEN CORROBORATION_COUNT = 2 THEN 70
        ELSE 40
      END AS CORROBORATION_CONFIDENCE_SCORE
    FROM TYPE_COMPONENTS
  ),
  COMBINED AS (
    SELECT
      *,
      CASE WHEN TARGET_SCORE_ELIGIBLE
        THEN ROUND(
          (
            0.60 * DATA_SENSITIVITY_SCORE
            + 0.25 * EXPOSURE_ACTIONABILITY_SCORE
            + IFF(
              RECORD_SCALE_SCORE IS NULL,
              0,
              0.15 * RECORD_SCALE_SCORE
            )
          )
          / IFF(RECORD_SCALE_SCORE IS NULL, 0.85, 1.00)
        )
      END AS IMPACT_SEVERITY_SCORE,
      CASE WHEN TARGET_SCORE_ELIGIBLE
        THEN ROUND(
          (
            0.35 * OWNERSHIP_EVIDENCE_SCORE
            + 0.25 * GROUNDING_CONFIDENCE_SCORE
            + 0.20 * CLAIM_PROOF_SCORE
            + 0.15 * CORROBORATION_CONFIDENCE_SCORE
            + IFF(
              ACTOR_NODE_KEY IS NULL,
              0,
              0.05 * ACTOR_CREDIBILITY_SCORE
            )
          )
          / IFF(ACTOR_NODE_KEY IS NULL, 0.95, 1.00)
        )
      END AS EVIDENCE_CONFIDENCE_SCORE
    FROM IMPACT_COMPONENTS
  ),
  FINAL AS (
    SELECT
      *,
      CASE WHEN TARGET_SCORE_ELIGIBLE
        THEN ROUND(
          0.80 * IMPACT_SEVERITY_SCORE
            + 0.20 * EVIDENCE_CONFIDENCE_SCORE
        )
      END AS TRIAGE_PRIORITY_SCORE
    FROM COMBINED
  )
  SELECT
    *,
    IMPACT_SEVERITY_SCORE AS TARGET_SEVERITY_SCORE,
    IMPACT_SEVERITY_SCORE AS FINAL_SEVERITY_SCORE,
    CASE
      WHEN IMPACT_SEVERITY_SCORE IS NULL THEN NULL
      WHEN IMPACT_SEVERITY_SCORE >= 80 THEN 'critical'
      WHEN IMPACT_SEVERITY_SCORE >= 60 THEN 'high'
      WHEN IMPACT_SEVERITY_SCORE >= 40 THEN 'medium'
      WHEN IMPACT_SEVERITY_SCORE >= 20 THEN 'low'
      ELSE 'informational'
    END AS IMPACT_SEVERITY_BAND,
    CASE
      WHEN IMPACT_SEVERITY_SCORE IS NULL THEN NULL
      WHEN IMPACT_SEVERITY_SCORE >= 80 THEN 'critical'
      WHEN IMPACT_SEVERITY_SCORE >= 60 THEN 'high'
      WHEN IMPACT_SEVERITY_SCORE >= 40 THEN 'medium'
      WHEN IMPACT_SEVERITY_SCORE >= 20 THEN 'low'
      ELSE 'informational'
    END AS TARGET_SEVERITY_BAND,
    CASE
      WHEN IMPACT_SEVERITY_SCORE IS NULL THEN NULL
      WHEN IMPACT_SEVERITY_SCORE >= 80 THEN 'critical'
      WHEN IMPACT_SEVERITY_SCORE >= 60 THEN 'high'
      WHEN IMPACT_SEVERITY_SCORE >= 40 THEN 'medium'
      WHEN IMPACT_SEVERITY_SCORE >= 20 THEN 'low'
      ELSE 'informational'
    END AS FINAL_SEVERITY_BAND,
    CASE
      WHEN EVIDENCE_CONFIDENCE_SCORE IS NULL THEN NULL
      WHEN EVIDENCE_CONFIDENCE_SCORE >= 85 THEN 'very_high'
      WHEN EVIDENCE_CONFIDENCE_SCORE >= 70 THEN 'high'
      WHEN EVIDENCE_CONFIDENCE_SCORE >= 50 THEN 'medium'
      ELSE 'low'
    END AS EVIDENCE_CONFIDENCE_BAND,
    CASE
      WHEN TRIAGE_PRIORITY_SCORE IS NULL THEN NULL
      WHEN TRIAGE_PRIORITY_SCORE >= 80 THEN 'critical'
      WHEN TRIAGE_PRIORITY_SCORE >= 60 THEN 'high'
      WHEN TRIAGE_PRIORITY_SCORE >= 40 THEN 'medium'
      WHEN TRIAGE_PRIORITY_SCORE >= 20 THEN 'low'
      ELSE 'informational'
    END AS TRIAGE_PRIORITY_BAND,
    CASE WHEN TARGET_SCORE_ELIGIBLE
      THEN SHA2(ORG_ID || '|' || CONTENT_SHA256)
    END AS INCIDENT_KEY,
    OBJECT_CONSTRUCT_KEEP_NULL(
      'data_sensitivity', DATA_SENSITIVITY_SCORE,
      'exposure_actionability', EXPOSURE_ACTIONABILITY_SCORE,
      'record_scale', RECORD_SCALE_SCORE,
      'ownership_evidence', OWNERSHIP_EVIDENCE_SCORE,
      'grounding', GROUNDING_CONFIDENCE_SCORE,
      'claim_proof', CLAIM_PROOF_SCORE,
      'corroboration', CORROBORATION_CONFIDENCE_SCORE,
      'actor_credibility', IFF(
        ACTOR_NODE_KEY IS NULL,
        NULL,
        ACTOR_CREDIBILITY_SCORE
      ),
      'impact_severity', IMPACT_SEVERITY_SCORE,
      'evidence_confidence', EVIDENCE_CONFIDENCE_SCORE,
      'triage_priority', TRIAGE_PRIORITY_SCORE
    ) AS SCORE_VECTOR,
    ARRAY_COMPACT(ARRAY_CONSTRUCT(
      IFF(TARGET_SCORE_ELIGIBLE,
        'grounded_target_ownership_confirmed', NULL),
      IFF(MAX_QUANTITY_CLAIMED IS NULL,
        'record_count_unknown_and_omitted', NULL),
      IFF(CORROBORATION_COUNT >= 3 AND DISPUTE_COUNT = 0,
        'corroborated_by_3_or_more_distinct_contents', NULL),
      IFF(CORROBORATION_COUNT = 2 AND DISPUTE_COUNT = 0,
        'corroborated_by_2_distinct_contents', NULL),
      IFF(CORROBORATION_COUNT <= 1,
        'single_distinct_content', NULL),
      IFF(MIRROR_SIGHTING_COUNT > 0,
        'same_content_mirrors_not_counted_as_corroboration', NULL),
      IFF(DISPUTE_COUNT > 0, 'claim_disputed', NULL),
      IFF(COALESCE(STRONG_INDICATOR_COUNT, 0) > 0,
        'strong_exposed_material_present', NULL),
      IFF(ACTOR_NODE_KEY IS NULL,
        'actor_not_identified_confidence_weight_omitted', NULL)
    )) AS SCORE_REASONS,
    'impact_confidence_priority_v3' AS SCORE_METHOD_VERSION
  FROM FINAL;

-- Target incidents only. DT_L4_DOCUMENT_SEVERITY retains non-target pages with
-- NULL scores so analysts can audit why they stopped before the dashboard.
CREATE OR REPLACE VIEW NOCTURNE.RAW.VW_L4_DOCUMENT_SEVERITY AS
  SELECT *
  FROM NOCTURNE.RAW.DT_L4_DOCUMENT_SEVERITY
  WHERE TARGET_SCORE_ELIGIBLE
    AND TARGET_SEVERITY_SCORE IS NOT NULL;

-- CONTENT_SHA256 defines the hackathon incident boundary. Mirrors reuse one
-- incident; differently written reports remain separate until event clustering
-- is introduced after the hackathon.
CREATE OR REPLACE VIEW NOCTURNE.RAW.VW_L4_INCIDENT_SEVERITY AS
  SELECT
    ORG_ID,
    INCIDENT_KEY,
    CONTENT_SHA256,
    ANY_VALUE(CANONICAL_NAME) AS CANONICAL_NAME,
    MAX_BY(ACTOR_NAME, TRIAGE_PRIORITY_SCORE) AS ACTOR_NAME,
    MAX_BY(ACTOR_NODE_KEY, TRIAGE_PRIORITY_SCORE) AS ACTOR_NODE_KEY,
    MAX(IMPACT_SEVERITY_SCORE) AS INCIDENT_IMPACT_SEVERITY_SCORE,
    MAX_BY(IMPACT_SEVERITY_BAND, IMPACT_SEVERITY_SCORE)
      AS INCIDENT_IMPACT_SEVERITY_BAND,
    MAX(EVIDENCE_CONFIDENCE_SCORE) AS INCIDENT_EVIDENCE_CONFIDENCE_SCORE,
    MAX_BY(EVIDENCE_CONFIDENCE_BAND, EVIDENCE_CONFIDENCE_SCORE)
      AS INCIDENT_EVIDENCE_CONFIDENCE_BAND,
    MAX(TRIAGE_PRIORITY_SCORE) AS INCIDENT_TRIAGE_PRIORITY_SCORE,
    MAX_BY(TRIAGE_PRIORITY_BAND, TRIAGE_PRIORITY_SCORE)
      AS INCIDENT_TRIAGE_PRIORITY_BAND,
    MAX_BY(SCORE_VECTOR, TRIAGE_PRIORITY_SCORE) AS SCORE_VECTOR,
    MAX_BY(SCORE_REASONS, TRIAGE_PRIORITY_SCORE) AS SCORE_REASONS,
    MAX_BY(LEAK_TYPE_LABELS, TRIAGE_PRIORITY_SCORE) AS LEAK_TYPE_LABELS,
    MAX_BY(URL, TRIAGE_PRIORITY_SCORE) AS TOP_URL,
    MAX_BY(TITLE, TRIAGE_PRIORITY_SCORE) AS TOP_TITLE,
    COUNT(DISTINCT DEDUPE_KEY) AS SIGHTING_COUNT,
    GREATEST(0, COUNT(DISTINCT DEDUPE_KEY) - 1)
      AS MIRROR_SIGHTING_COUNT,
    MAX(CORROBORATION_COUNT) AS CORROBORATION_COUNT,
    MAX(ACTOR_CREDIBILITY_SCORE) AS ACTOR_CREDIBILITY_SCORE,
    MIN(FETCHED_AT) AS FIRST_SEEN,
    MAX(FETCHED_AT) AS LAST_SEEN,
    'target_incident' AS GRAPH_SCOPE
  FROM NOCTURNE.RAW.VW_L4_DOCUMENT_SEVERITY
  GROUP BY ORG_ID, INCIDENT_KEY, CONTENT_SHA256;

CREATE OR REPLACE VIEW NOCTURNE.RAW.VW_L4_ORG_POSTURE AS
  SELECT
    ORG_ID,
    ANY_VALUE(CANONICAL_NAME) AS CANONICAL_NAME,
    MAX(INCIDENT_IMPACT_SEVERITY_SCORE) AS TOP_IMPACT_SEVERITY_SCORE,
    MAX_BY(
      INCIDENT_IMPACT_SEVERITY_BAND,
      INCIDENT_IMPACT_SEVERITY_SCORE
    ) AS TOP_IMPACT_SEVERITY_BAND,
    MAX(INCIDENT_TRIAGE_PRIORITY_SCORE) AS TOP_TRIAGE_PRIORITY_SCORE,
    MAX_BY(
      INCIDENT_TRIAGE_PRIORITY_BAND,
      INCIDENT_TRIAGE_PRIORITY_SCORE
    ) AS TOP_TRIAGE_PRIORITY_BAND,
    COUNT(*) AS INCIDENT_COUNT,
    COUNT_IF(INCIDENT_IMPACT_SEVERITY_BAND = 'critical')
      AS CRITICAL_INCIDENTS,
    COUNT_IF(INCIDENT_IMPACT_SEVERITY_BAND = 'high') AS HIGH_INCIDENTS,
    COUNT(DISTINCT ACTOR_NODE_KEY) AS DISTINCT_ACTORS,
    SUM(SIGHTING_COUNT) AS TOTAL_SIGHTINGS,
    SUM(MIRROR_SIGHTING_COUNT) AS TOTAL_MIRROR_SIGHTINGS,
    MAX(LAST_SEEN) AS LAST_ACTIVITY
  FROM NOCTURNE.RAW.VW_L4_INCIDENT_SEVERITY
  GROUP BY ORG_ID;

-- Safe validation examples. Both violation queries must return zero.
-- SELECT COUNT(*) AS INVALID_TARGET_SCORES
-- FROM NOCTURNE.RAW.DT_L4_DOCUMENT_SEVERITY
-- WHERE TARGET_SEVERITY_SCORE IS NOT NULL
--   AND (
--     NOT TARGET_ALERT_ELIGIBLE
--     OR L2_ROUTE <> 'target_confirmed'
--     OR GRAPH_SCOPE <> 'target_incident'
--     OR NOT TARGET_LEAK_RELATION_GROUNDED
--   );
--
-- SELECT COUNT(*) AS SCORE_RANGE_VIOLATIONS
-- FROM NOCTURNE.RAW.VW_L4_DOCUMENT_SEVERITY
-- WHERE IMPACT_SEVERITY_SCORE NOT BETWEEN 0 AND 100
--   OR EVIDENCE_CONFIDENCE_SCORE NOT BETWEEN 0 AND 100
--   OR TRIAGE_PRIORITY_SCORE NOT BETWEEN 0 AND 100;
--
-- SELECT ORG_ID, TITLE, LEAK_TYPE_LABELS,
--   IMPACT_SEVERITY_SCORE, IMPACT_SEVERITY_BAND,
--   EVIDENCE_CONFIDENCE_SCORE, EVIDENCE_CONFIDENCE_BAND,
--   TRIAGE_PRIORITY_SCORE, TRIAGE_PRIORITY_BAND, SCORE_VECTOR
-- FROM NOCTURNE.RAW.VW_L4_DOCUMENT_SEVERITY
-- ORDER BY TRIAGE_PRIORITY_SCORE DESC;
