-- =============================================================================
-- Nocturne Pipeline: Step 16 - Dashboard Interface
-- =============================================================================
-- This schema is the stable read boundary for the dashboard. UI/backend code
-- must read these views instead of depending directly on pipeline internals.
--
-- The interface supports the Command Center and Breach Monitor with:
--   * one typed incident projection, reusable by the list/detail pages; and
--   * one organization-level summary containing KPIs and cascade counts; and
--   * one audit-safe monitor projection covering confirmed target incidents,
--     target-related pages needing review, and other-organization leaks; and
--   * incident-scoped grounded claims, indicator counts, graph nodes, and graph
--     edges for the detail and knowledge-graph screens.
--
-- No raw source text, exact indicator values, prompts, or raw AI payloads are
-- exposed here. Evidence is limited to accepted text copied from the masked L2
-- EVIDENCE_INPUT. Every view remains organization-scoped through ORG_ID.
-- =============================================================================

USE ROLE ACCOUNTADMIN;

CREATE SCHEMA IF NOT EXISTS NOCTURNE.DASHBOARD;
USE SCHEMA NOCTURNE.DASHBOARD;

-- Reusable incident contract for Command Center, Breach Monitor, and Incident
-- Detail. One representative document supplies document-level routing fields;
-- the incident view supplies content-level aggregation and cached AI insight.
CREATE OR REPLACE VIEW NOCTURNE.DASHBOARD.VW_INCIDENTS AS
  WITH REPRESENTATIVE_DOCUMENT AS (
    SELECT
      ORG_ID,
      INCIDENT_KEY,
      SOURCE,
      L2_ROUTE,
      ROUTING_REASON,
      RELATIONSHIP_LABEL,
      MAX_QUANTITY_CLAIMED,
      EXACT_GROUNDED_CLAIM_COUNT,
      NORMALIZED_GROUNDED_CLAIM_COUNT
    FROM NOCTURNE.RAW.VW_L4_DOCUMENT_SEVERITY
    QUALIFY ROW_NUMBER() OVER (
      PARTITION BY ORG_ID, INCIDENT_KEY
      ORDER BY TRIAGE_PRIORITY_SCORE DESC, FETCHED_AT DESC, DOC_ID
    ) = 1
  )
  SELECT
    INCIDENT.ORG_ID,
    ORGANIZATION.CANONICAL_NAME AS ORGANIZATION_NAME,
    ORGANIZATION.DOMAINS[0]::STRING AS ORGANIZATION_DOMAIN,
    INCIDENT.INCIDENT_KEY,
    INCIDENT.CONTENT_SHA256,
    INCIDENT.TOP_TITLE,
    INCIDENT.TOP_URL,
    DOCUMENT.SOURCE,
    DOCUMENT.L2_ROUTE,
    DOCUMENT.ROUTING_REASON,
    DOCUMENT.RELATIONSHIP_LABEL,
    INCIDENT.LEAK_TYPE_LABELS,
    DOCUMENT.MAX_QUANTITY_CLAIMED AS QUANTITY_CLAIMED,
    INCIDENT.INCIDENT_IMPACT_SEVERITY_SCORE AS IMPACT_SEVERITY_SCORE,
    INCIDENT.INCIDENT_IMPACT_SEVERITY_BAND AS IMPACT_SEVERITY_BAND,
    INCIDENT.INCIDENT_EVIDENCE_CONFIDENCE_SCORE
      AS EVIDENCE_CONFIDENCE_SCORE,
    INCIDENT.INCIDENT_EVIDENCE_CONFIDENCE_BAND
      AS EVIDENCE_CONFIDENCE_BAND,
    INCIDENT.INCIDENT_TRIAGE_PRIORITY_SCORE AS TRIAGE_PRIORITY_SCORE,
    INCIDENT.INCIDENT_TRIAGE_PRIORITY_BAND AS TRIAGE_PRIORITY_BAND,
    INCIDENT.SCORE_VECTOR,
    INCIDENT.SCORE_REASONS,
    INCIDENT.CORROBORATION_COUNT,
    INCIDENT.SIGHTING_COUNT,
    INCIDENT.MIRROR_SIGHTING_COUNT,
    INCIDENT.ACTOR_NODE_KEY,
    INCIDENT.ACTOR_NAME,
    INCIDENT.ACTOR_CREDIBILITY_SCORE,
    CASE
      WHEN DOCUMENT.EXACT_GROUNDED_CLAIM_COUNT > 0 THEN 'exact'
      WHEN DOCUMENT.NORMALIZED_GROUNDED_CLAIM_COUNT > 0 THEN 'normalized'
      ELSE NULL
    END AS GROUNDING_LEVEL,
    INCIDENT.FIRST_SEEN,
    INCIDENT.LAST_SEEN,
    INCIDENT.GRAPH_SCOPE,
    INCIDENT.INSIGHT_AI_STATUS,
    INCIDENT.INSIGHT_HEADLINE,
    INCIDENT.EXECUTIVE_SUMMARY,
    INCIDENT.WHAT_HAPPENED,
    INCIDENT.BUSINESS_IMPACT,
    INCIDENT.RECOMMENDED_ACTIONS,
    INCIDENT.CONFIDENCE_ASSESSMENT,
    INCIDENT.INSIGHT_CAVEATS,
    INCIDENT.INSIGHT_PROMPT_VERSION,
    INCIDENT.INSIGHT_MODEL_NAME,
    INCIDENT.INSIGHT_CALLED_AT,
    'new' AS REMEDIATION_STATUS
  FROM NOCTURNE.RAW.VW_L4_INCIDENT_INSIGHTS AS INCIDENT
  INNER JOIN NOCTURNE.CONFIG.MONITORED_ORGANIZATIONS AS ORGANIZATION
    ON ORGANIZATION.ORG_ID = INCIDENT.ORG_ID
  LEFT JOIN REPRESENTATIVE_DOCUMENT AS DOCUMENT
    ON DOCUMENT.ORG_ID = INCIDENT.ORG_ID
    AND DOCUMENT.INCIDENT_KEY = INCIDENT.INCIDENT_KEY;

-- Accepted target claims and their masked supporting excerpts. L2 was given
-- EVIDENCE_INPUT rather than RAW_TEXT, so exact indicator spans have already
-- been replaced with [REDACTED_INDICATOR]. Length caps keep API responses and
-- browser rendering bounded without changing the stored analyst evidence.
CREATE OR REPLACE VIEW NOCTURNE.DASHBOARD.VW_INCIDENT_CLAIMS AS
  SELECT
    INCIDENT.ORG_ID,
    INCIDENT.INCIDENT_KEY,
    CLAIM.DOC_ID,
    CLAIM.DEDUPE_KEY,
    CLAIM.CONTENT_SHA256,
    CLAIM.CLAIM_KEY,
    LEFT(CLAIM.STATEMENT, 2000) AS CLAIM_STATEMENT,
    LENGTH(CLAIM.STATEMENT) > 2000 AS CLAIM_STATEMENT_TRUNCATED,
    CLAIM.CLAIM_STATUS,
    CLAIM.CLAIM_STATUS_EXTRACTED,
    CLAIM.QUANTITY_CLAIMED,
    CLAIM.GROUNDING_LEVEL,
    LEFT(CLAIM.EVIDENCE_TEXT, 2000) AS MASKED_EVIDENCE_TEXT,
    LENGTH(CLAIM.EVIDENCE_TEXT) > 2000 AS EVIDENCE_TEXT_TRUNCATED,
    CLAIM.EVIDENCE_START,
    CLAIM.EVIDENCE_END,
    CLAIM.SELECTED_WINDOW_ID,
    CLAIM.SUBJECT_NODE_KEY,
    CLAIM.SUBJECT_NAME,
    CLAIM.CORROBORATION_COUNT,
    CLAIM.SIGHTING_COUNT,
    CLAIM.MIRROR_SIGHTING_COUNT,
    CLAIM.UNIQUE_CLAIM_COUNT,
    CLAIM.DISPUTE_COUNT,
    CLAIM.GRAPH_SCOPE
  FROM NOCTURNE.DASHBOARD.VW_INCIDENTS AS INCIDENT
  INNER JOIN NOCTURNE.RAW.DT_L3_CLAIM_CORROBORATION AS CLAIM
    ON CLAIM.ORG_ID = INCIDENT.ORG_ID
    AND CLAIM.CONTENT_SHA256 = INCIDENT.CONTENT_SHA256
  WHERE CLAIM.IS_ACCEPTED
    AND CLAIM.IS_GROUNDED
    AND CLAIM.GRAPH_SCOPE = 'target_incident';

-- Indicator counts only. Exact matched values and their source offsets remain
-- inside the restricted RAW layer and are never projected to the dashboard.
CREATE OR REPLACE VIEW NOCTURNE.DASHBOARD.VW_INCIDENT_INDICATOR_COUNTS AS
  WITH REPRESENTATIVE_PAGE AS (
    SELECT
      INCIDENT.ORG_ID,
      INCIDENT.INCIDENT_KEY,
      PAGE.DOC_ID,
      PAGE.DEDUPE_KEY,
      PAGE.INDICATORS_FOUND,
      PAGE.FETCHED_AT
    FROM NOCTURNE.DASHBOARD.VW_INCIDENTS AS INCIDENT
    INNER JOIN NOCTURNE.RAW.DT_REGEX_INDICATORS AS PAGE
      ON PAGE.ORG_ID = INCIDENT.ORG_ID
      AND PAGE.CONTENT_SHA256 = INCIDENT.CONTENT_SHA256
    QUALIFY ROW_NUMBER() OVER (
      PARTITION BY INCIDENT.ORG_ID, INCIDENT.INCIDENT_KEY
      ORDER BY PAGE.FETCHED_AT DESC, PAGE.DOC_ID
    ) = 1
  )
  SELECT
    PAGE.ORG_ID,
    PAGE.INCIDENT_KEY,
    PAGE.DOC_ID,
    PAGE.DEDUPE_KEY,
    INDICATOR.KEY::STRING AS INDICATOR_TYPE,
    INDICATOR.VALUE::NUMBER AS INDICATOR_COUNT,
    PAGE.INDICATORS_FOUND:strong_count::NUMBER AS STRONG_INDICATOR_COUNT,
    PAGE.INDICATORS_FOUND:medium_count::NUMBER AS MEDIUM_INDICATOR_COUNT,
    PAGE.INDICATORS_FOUND:weak_count::NUMBER AS WEAK_INDICATOR_COUNT,
    PAGE.INDICATORS_FOUND:evidence_score::NUMBER AS INDICATOR_EVIDENCE_SCORE
  FROM REPRESENTATIVE_PAGE AS PAGE,
    LATERAL FLATTEN(INPUT => PAGE.INDICATORS_FOUND:counts) AS INDICATOR
  WHERE INDICATOR.VALUE::NUMBER > 0;

-- Incident graph nodes are derived from the exact promoted component for that
-- incident. Claim nodes are included explicitly because DIM_GRAPH_NODE stores
-- entity nodes only. Keys retain ORG_ID isolation from the pipeline.
CREATE OR REPLACE VIEW NOCTURNE.DASHBOARD.VW_INCIDENT_GRAPH_NODES AS
  WITH ENTITY_ENDPOINTS AS (
    SELECT
      INCIDENT.ORG_ID,
      INCIDENT.INCIDENT_KEY,
      EDGE.DEDUPE_KEY,
      EDGE.CONTENT_SHA256,
      EDGE.SOURCE_KEY AS NODE_KEY,
      EDGE.FETCHED_AT
    FROM NOCTURNE.DASHBOARD.VW_INCIDENTS AS INCIDENT
    INNER JOIN NOCTURNE.RAW.DT_L3_PROMOTED_EDGES AS EDGE
      ON EDGE.ORG_ID = INCIDENT.ORG_ID
      AND EDGE.CONTENT_SHA256 = INCIDENT.CONTENT_SHA256
    WHERE EDGE.SOURCE_KIND = 'entity'
    UNION ALL
    SELECT
      INCIDENT.ORG_ID,
      INCIDENT.INCIDENT_KEY,
      EDGE.DEDUPE_KEY,
      EDGE.CONTENT_SHA256,
      EDGE.TARGET_KEY AS NODE_KEY,
      EDGE.FETCHED_AT
    FROM NOCTURNE.DASHBOARD.VW_INCIDENTS AS INCIDENT
    INNER JOIN NOCTURNE.RAW.DT_L3_PROMOTED_EDGES AS EDGE
      ON EDGE.ORG_ID = INCIDENT.ORG_ID
      AND EDGE.CONTENT_SHA256 = INCIDENT.CONTENT_SHA256
    WHERE EDGE.TARGET_KIND = 'entity'
  ),
  ENTITY_NODES AS (
    SELECT
      ENDPOINT.ORG_ID,
      ENDPOINT.INCIDENT_KEY,
      ENDPOINT.NODE_KEY,
      NODE.NODE_TYPE,
      NODE.NORMALIZED_NAME,
      NODE.DISPLAY_NAME,
      MODE(NODE.DISPLAY_NAME) AS NODE_DESCRIPTION,
      NODE.IS_MONITORED_ORG,
      MODE(ENTITY.ENTITY_MATCH_STATUS) AS ENTITY_MATCH_STATUS,
      MODE(ENTITY.ENTITY_MATCH_METHOD) AS ENTITY_MATCH_METHOD,
      MAX(ENTITY.ENTITY_MATCH_CONFIDENCE) AS ENTITY_MATCH_CONFIDENCE,
      COUNT(*) AS MENTION_COUNT,
      COUNT(DISTINCT ENDPOINT.DEDUPE_KEY) AS SIGHTING_COUNT,
      COUNT(DISTINCT ENDPOINT.CONTENT_SHA256) AS DOC_COUNT,
      GREATEST(
        0,
        COUNT(DISTINCT ENDPOINT.DEDUPE_KEY)
          - COUNT(DISTINCT ENDPOINT.CONTENT_SHA256)
      ) AS MIRROR_SIGHTING_COUNT,
      MIN(ENDPOINT.FETCHED_AT) AS FIRST_SEEN,
      MAX(ENDPOINT.FETCHED_AT) AS LAST_SEEN,
      'target_incident' AS GRAPH_SCOPE
    FROM ENTITY_ENDPOINTS AS ENDPOINT
    INNER JOIN NOCTURNE.RAW.DIM_GRAPH_NODE AS NODE
      ON NODE.ORG_ID = ENDPOINT.ORG_ID
      AND NODE.NODE_KEY = ENDPOINT.NODE_KEY
    LEFT JOIN NOCTURNE.RAW.DT_L2_ENTITIES AS ENTITY
      ON ENTITY.ORG_ID = ENDPOINT.ORG_ID
      AND ENTITY.DEDUPE_KEY = ENDPOINT.DEDUPE_KEY
      AND ENTITY.NODE_KEY = ENDPOINT.NODE_KEY
      AND ENTITY.IS_ACCEPTED
      AND ENTITY.IS_GROUNDED
    GROUP BY
      ENDPOINT.ORG_ID,
      ENDPOINT.INCIDENT_KEY,
      ENDPOINT.NODE_KEY,
      NODE.NODE_TYPE,
      NODE.NORMALIZED_NAME,
      NODE.DISPLAY_NAME,
      NODE.IS_MONITORED_ORG
  ),
  CLAIM_NODES AS (
    SELECT
      CLAIM.ORG_ID,
      CLAIM.INCIDENT_KEY,
      CLAIM.CLAIM_KEY AS NODE_KEY,
      'claim' AS NODE_TYPE,
      NULL::VARCHAR AS NORMALIZED_NAME,
      LEFT(CLAIM.CLAIM_STATEMENT, 160) AS DISPLAY_NAME,
      MAX(CLAIM.CLAIM_STATEMENT) AS NODE_DESCRIPTION,
      FALSE AS IS_MONITORED_ORG,
      NULL::VARCHAR AS ENTITY_MATCH_STATUS,
      NULL::VARCHAR AS ENTITY_MATCH_METHOD,
      NULL::NUMBER AS ENTITY_MATCH_CONFIDENCE,
      COUNT(*) AS MENTION_COUNT,
      COUNT(DISTINCT CLAIM.DEDUPE_KEY) AS SIGHTING_COUNT,
      COUNT(DISTINCT CLAIM.CONTENT_SHA256) AS DOC_COUNT,
      MAX(CLAIM.MIRROR_SIGHTING_COUNT) AS MIRROR_SIGHTING_COUNT,
      MIN(INCIDENT.FIRST_SEEN) AS FIRST_SEEN,
      MAX(INCIDENT.LAST_SEEN) AS LAST_SEEN,
      'target_incident' AS GRAPH_SCOPE
    FROM NOCTURNE.DASHBOARD.VW_INCIDENT_CLAIMS AS CLAIM
    INNER JOIN NOCTURNE.DASHBOARD.VW_INCIDENTS AS INCIDENT
      ON INCIDENT.ORG_ID = CLAIM.ORG_ID
      AND INCIDENT.INCIDENT_KEY = CLAIM.INCIDENT_KEY
    GROUP BY
      CLAIM.ORG_ID,
      CLAIM.INCIDENT_KEY,
      CLAIM.CLAIM_KEY,
      LEFT(CLAIM.CLAIM_STATEMENT, 160)
  )
  SELECT * FROM ENTITY_NODES
  UNION ALL
  SELECT * FROM CLAIM_NODES;

-- Edges are grouped within an incident rather than using the organization-wide
-- aggregate, preventing graph context from another incident leaking into the
-- selected incident's visualization.
CREATE OR REPLACE VIEW NOCTURNE.DASHBOARD.VW_INCIDENT_GRAPH_EDGES AS
  SELECT
    INCIDENT.ORG_ID,
    INCIDENT.INCIDENT_KEY,
    SHA2(
      INCIDENT.ORG_ID || '|' || INCIDENT.INCIDENT_KEY || '|'
        || EDGE.SOURCE_KEY || '|' || EDGE.EDGE_TYPE || '|' || EDGE.TARGET_KEY
    ) AS GRAPH_EDGE_KEY,
    EDGE.SOURCE_KEY,
    EDGE.EDGE_TYPE,
    EDGE.TARGET_KEY,
    MODE(EDGE.SOURCE_KIND) AS SOURCE_KIND,
    MODE(EDGE.SOURCE_TYPE) AS SOURCE_TYPE,
    MODE(EDGE.TARGET_KIND) AS TARGET_KIND,
    MODE(EDGE.TARGET_TYPE) AS TARGET_TYPE,
    LEFT(MAX(EDGE.EVIDENCE_TEXT), 1200) AS SAMPLE_EVIDENCE_TEXT,
    MODE(EDGE.GROUNDING_LEVEL) AS GROUNDING_LEVEL,
    MAX(EDGE.EVIDENCE_START) AS EVIDENCE_START,
    MAX(EDGE.EVIDENCE_END) AS EVIDENCE_END,
    MODE(EDGE.SELECTED_WINDOW_ID) AS SELECTED_WINDOW_ID,
    COUNT(*) AS MENTION_COUNT,
    COUNT(DISTINCT EDGE.DEDUPE_KEY) AS SIGHTING_COUNT,
    COUNT(DISTINCT EDGE.CONTENT_SHA256) AS DOC_COUNT,
    GREATEST(
      0,
      COUNT(DISTINCT EDGE.DEDUPE_KEY)
        - COUNT(DISTINCT EDGE.CONTENT_SHA256)
    ) AS MIRROR_SIGHTING_COUNT,
    MIN(EDGE.FETCHED_AT) AS FIRST_SEEN,
    MAX(EDGE.FETCHED_AT) AS LAST_SEEN,
    'target_incident' AS GRAPH_SCOPE
  FROM NOCTURNE.DASHBOARD.VW_INCIDENTS AS INCIDENT
  INNER JOIN NOCTURNE.RAW.DT_L3_PROMOTED_EDGES AS EDGE
    ON EDGE.ORG_ID = INCIDENT.ORG_ID
    AND EDGE.CONTENT_SHA256 = INCIDENT.CONTENT_SHA256
  GROUP BY
    INCIDENT.ORG_ID,
    INCIDENT.INCIDENT_KEY,
    EDGE.SOURCE_KEY,
    EDGE.EDGE_TYPE,
    EDGE.TARGET_KEY;

-- Organization-wide graph contracts power the Actor Network. They aggregate
-- only promoted target-incident components and retain ORG_ID in every key, so
-- switching tenants cannot merge actors, claims, or relationships.
CREATE OR REPLACE VIEW NOCTURNE.DASHBOARD.VW_KNOWLEDGE_GRAPH_NODES AS
  SELECT
    ORG_ID,
    NODE_KEY,
    MODE(NODE_TYPE) AS NODE_TYPE,
    MODE(NORMALIZED_NAME) AS NORMALIZED_NAME,
    MODE(DISPLAY_NAME) AS DISPLAY_NAME,
    MODE(NODE_DESCRIPTION) AS NODE_DESCRIPTION,
    BOOLOR_AGG(IS_MONITORED_ORG) AS IS_MONITORED_ORG,
    MODE(ENTITY_MATCH_STATUS) AS ENTITY_MATCH_STATUS,
    MODE(ENTITY_MATCH_METHOD) AS ENTITY_MATCH_METHOD,
    MAX(ENTITY_MATCH_CONFIDENCE) AS ENTITY_MATCH_CONFIDENCE,
    SUM(MENTION_COUNT) AS MENTION_COUNT,
    SUM(SIGHTING_COUNT) AS SIGHTING_COUNT,
    SUM(DOC_COUNT) AS DOC_COUNT,
    SUM(MIRROR_SIGHTING_COUNT) AS MIRROR_SIGHTING_COUNT,
    MIN(FIRST_SEEN) AS FIRST_SEEN,
    MAX(LAST_SEEN) AS LAST_SEEN,
    'target_incident' AS GRAPH_SCOPE
  FROM NOCTURNE.DASHBOARD.VW_INCIDENT_GRAPH_NODES
  GROUP BY ORG_ID, NODE_KEY;

CREATE OR REPLACE VIEW NOCTURNE.DASHBOARD.VW_KNOWLEDGE_GRAPH_EDGES AS
  SELECT
    ORG_ID,
    SHA2(ORG_ID || '|' || SOURCE_KEY || '|' || EDGE_TYPE || '|' || TARGET_KEY)
      AS GRAPH_EDGE_KEY,
    SOURCE_KEY,
    EDGE_TYPE,
    TARGET_KEY,
    MODE(SOURCE_KIND) AS SOURCE_KIND,
    MODE(SOURCE_TYPE) AS SOURCE_TYPE,
    MODE(TARGET_KIND) AS TARGET_KIND,
    MODE(TARGET_TYPE) AS TARGET_TYPE,
    LEFT(MAX(SAMPLE_EVIDENCE_TEXT), 1200) AS SAMPLE_EVIDENCE_TEXT,
    MODE(GROUNDING_LEVEL) AS GROUNDING_LEVEL,
    MAX(EVIDENCE_START) AS EVIDENCE_START,
    MAX(EVIDENCE_END) AS EVIDENCE_END,
    MODE(SELECTED_WINDOW_ID) AS SELECTED_WINDOW_ID,
    SUM(MENTION_COUNT) AS MENTION_COUNT,
    SUM(SIGHTING_COUNT) AS SIGHTING_COUNT,
    SUM(DOC_COUNT) AS DOC_COUNT,
    SUM(MIRROR_SIGHTING_COUNT) AS MIRROR_SIGHTING_COUNT,
    MIN(FIRST_SEEN) AS FIRST_SEEN,
    MAX(LAST_SEEN) AS LAST_SEEN,
    'target_incident' AS GRAPH_SCOPE
  FROM NOCTURNE.DASHBOARD.VW_INCIDENT_GRAPH_EDGES
  GROUP BY ORG_ID, SOURCE_KEY, EDGE_TYPE, TARGET_KEY;

-- Actor credibility is evidence support, not probability or threat severity.
-- Marketplace names are safe graph context. Contact-channel values stay in
-- Snowflake; the dashboard receives only their count.
CREATE OR REPLACE VIEW NOCTURNE.DASHBOARD.VW_THREAT_ACTORS AS
  WITH CONTACT_COUNTS AS (
    SELECT
      ORG_ID,
      SOURCE_KEY AS ACTOR_NODE_KEY,
      COUNT(DISTINCT TARGET_KEY) AS CONTACT_CHANNEL_COUNT
    FROM NOCTURNE.RAW.DT_L3_PROMOTED_EDGES
    WHERE EDGE_TYPE = 'CONTACTED_VIA'
      AND SOURCE_TYPE = 'actor_alias'
      AND TARGET_TYPE = 'contact_channel'
    GROUP BY ORG_ID, SOURCE_KEY
  )
  SELECT
    ACTOR.ORG_ID,
    ACTOR.ACTOR_NODE_KEY,
    ACTOR.ACTOR_NAME,
    ACTOR.TOTAL_CLAIM_COUNT,
    ACTOR.CORROBORATED_CLAIM_COUNT,
    ACTOR.SELF_EVIDENCED_CLAIM_COUNT,
    ACTOR.DISPUTED_CLAIM_COUNT,
    ACTOR.DOC_COUNT,
    ACTOR.SIGHTING_COUNT,
    ACTOR.MIRROR_SIGHTING_COUNT,
    ACTOR.MARKETPLACE_COUNT,
    ACTOR.MARKETPLACES,
    COALESCE(CONTACT.CONTACT_CHANNEL_COUNT, 0) AS CONTACT_CHANNEL_COUNT,
    ACTOR.CORROBORATION_COMPONENT,
    ACTOR.SELF_EVIDENCE_COMPONENT,
    ACTOR.INDEPENDENT_HISTORY_COMPONENT,
    ACTOR.CLAIM_HISTORY_COMPONENT,
    ACTOR.DISPUTE_PENALTY,
    ACTOR.ACTOR_CREDIBILITY_SCORE,
    ACTOR.ACTOR_METHOD_VERSION,
    ACTOR.FIRST_SEEN,
    ACTOR.LAST_SEEN,
    ACTOR.GRAPH_SCOPE
  FROM NOCTURNE.RAW.DT_L3_ACTOR_CREDIBILITY AS ACTOR
  INNER JOIN NOCTURNE.CONFIG.MONITORED_ORGANIZATIONS AS ORGANIZATION
    ON ORGANIZATION.ORG_ID = ACTOR.ORG_ID
    AND ORGANIZATION.ENABLED = TRUE
  LEFT JOIN CONTACT_COUNTS AS CONTACT
    ON CONTACT.ORG_ID = ACTOR.ORG_ID
    AND CONTACT.ACTOR_NODE_KEY = ACTOR.ACTOR_NODE_KEY
  WHERE ACTOR.ACTOR_NAME IS NOT NULL;

-- Stable contract for the three Breach Monitor categories. Confirmed incidents
-- remain incident-level rows, while stopped or rejected candidates remain
-- document-level rows so their routing decision can be audited. Clear no-leak
-- results are intentionally excluded from a breach-focused screen.
--
-- A target-confirmed document can briefly exist before leak-type classification
-- and L4 finish. PENDING_CONFIRMED keeps it visible without fabricating scores;
-- it is replaced by the incident-level row once VW_INCIDENTS contains it.
-- Final-stage incidents with evidence confidence below 50 stay visible with
-- their detail page, but route to Needs Review instead of Confirmed Breach.
CREATE OR REPLACE VIEW NOCTURNE.DASHBOARD.VW_BREACH_MONITOR AS
  WITH CONFIRMED_INCIDENTS AS (
    SELECT
      INCIDENT.ORG_ID,
      INCIDENT.ORGANIZATION_NAME,
      INCIDENT.ORGANIZATION_DOMAIN,
      INCIDENT.INCIDENT_KEY AS MONITOR_KEY,
      INCIDENT.INCIDENT_KEY,
      NULL::VARCHAR AS DOC_ID,
      NULL::VARCHAR AS DEDUPE_KEY,
      INCIDENT.CONTENT_SHA256,
      INCIDENT.TOP_TITLE AS TITLE,
      INCIDENT.TOP_URL AS URL,
      INCIDENT.SOURCE,
      INCIDENT.FIRST_SEEN AS DISCOVERED_AT,
      IFF(
        COALESCE(INCIDENT.EVIDENCE_CONFIDENCE_SCORE, 0) < 50,
        'needs_review',
        'confirmed_yours'
      ) AS MONITOR_STATUS,
      IFF(
        COALESCE(INCIDENT.EVIDENCE_CONFIDENCE_SCORE, 0) < 50,
        'incident_ready_low_confidence',
        'incident_ready'
      ) AS PIPELINE_STATE,
      'success' AS RELATIONSHIP_AI_STATUS,
      INCIDENT.RELATIONSHIP_LABEL,
      INCIDENT.L2_ROUTE,
      INCIDENT.ROUTING_REASON,
      INCIDENT.LEAK_TYPE_LABELS,
      INCIDENT.QUANTITY_CLAIMED,
      INCIDENT.IMPACT_SEVERITY_SCORE,
      INCIDENT.IMPACT_SEVERITY_BAND,
      INCIDENT.EVIDENCE_CONFIDENCE_SCORE,
      INCIDENT.EVIDENCE_CONFIDENCE_BAND,
      INCIDENT.TRIAGE_PRIORITY_SCORE,
      INCIDENT.TRIAGE_PRIORITY_BAND,
      INCIDENT.ACTOR_NODE_KEY,
      INCIDENT.ACTOR_NAME,
      INCIDENT.ACTOR_CREDIBILITY_SCORE,
      INCIDENT.GROUNDING_LEVEL,
      INCIDENT.REMEDIATION_STATUS,
      TRUE AS DETAIL_AVAILABLE
    FROM NOCTURNE.DASHBOARD.VW_INCIDENTS AS INCIDENT
  ),
  CLASSIFIED_PAGES AS (
    SELECT
      PAGE.ORG_ID,
      ORGANIZATION.CANONICAL_NAME AS ORGANIZATION_NAME,
      ORGANIZATION.DOMAINS[0]::STRING AS ORGANIZATION_DOMAIN,
      PAGE.DOC_ID,
      PAGE.DEDUPE_KEY,
      PAGE.CONTENT_SHA256,
      PAGE.TITLE,
      PAGE.URL,
      PAGE.SOURCE,
      PAGE.FETCHED_AT AS DISCOVERED_AT,
      PAGE.RELATIONSHIP_AI_STATUS,
      PAGE.RELATIONSHIP_LABEL,
      ROUTING.L2_ROUTE,
      ROUTING.ROUTING_REASON,
      ROUTING.EXTRACTION_STATUS,
      CASE
        WHEN ROUTING.L2_ROUTE = 'target_confirmed'
          THEN 'confirmed_yours'
        WHEN ROUTING.L2_ROUTE = 'other_organization_confirmed'
          OR PAGE.RELATIONSHIP_LABEL = 'other_organization_leak'
          THEN 'another_company'
        ELSE 'needs_review'
      END AS MONITOR_STATUS,
      CASE
        WHEN PAGE.RELATIONSHIP_AI_STATUS <> 'success'
          THEN 'relationship_ai_error'
        WHEN ROUTING.L2_ROUTE = 'target_confirmed'
          THEN 'awaiting_leak_type_or_severity'
        WHEN ROUTING.L2_ROUTE IS NOT NULL
          THEN 'stopped_after_l2'
        ELSE 'stopped_after_l1'
      END AS PIPELINE_STATE,
      CASE
        WHEN PAGE.RELATIONSHIP_AI_STATUS <> 'success'
          THEN 'cached_relationship_classification_failed'
        WHEN ROUTING.ROUTING_REASON IS NOT NULL
          THEN ROUTING.ROUTING_REASON
        WHEN PAGE.RELATIONSHIP_LABEL = 'target_mentioned_no_leak'
          THEN 'target_mention_without_leak_classification'
        WHEN PAGE.RELATIONSHIP_LABEL = 'other_organization_leak'
          THEN 'l1_classified_leak_for_another_organization'
        WHEN PAGE.RELATIONSHIP_LABEL = 'target_data_leak'
          THEN 'awaiting_l2_ownership_resolution'
        ELSE 'stopped_after_relationship_classification'
      END AS EFFECTIVE_ROUTING_REASON
    FROM NOCTURNE.RAW.DT_PAGE_RELATIONSHIP_CLASSIFICATION AS PAGE
    INNER JOIN NOCTURNE.CONFIG.MONITORED_ORGANIZATIONS AS ORGANIZATION
      ON ORGANIZATION.ORG_ID = PAGE.ORG_ID
      AND ORGANIZATION.ENABLED = TRUE
    LEFT JOIN NOCTURNE.RAW.DT_L2_ROUTING AS ROUTING
      ON ROUTING.ORG_ID = PAGE.ORG_ID
      AND ROUTING.DEDUPE_KEY = PAGE.DEDUPE_KEY
    WHERE PAGE.RELATIONSHIP_AI_STATUS <> 'success'
      OR PAGE.RELATIONSHIP_LABEL IN (
        'target_data_leak',
        'target_mentioned_no_leak',
        'other_organization_leak'
      )
  ),
  PENDING_CONFIRMED AS (
    SELECT
      PAGE.ORG_ID,
      PAGE.ORGANIZATION_NAME,
      PAGE.ORGANIZATION_DOMAIN,
      SHA2(PAGE.ORG_ID || '|confirmed_page|' || PAGE.DEDUPE_KEY)
        AS MONITOR_KEY,
      NULL::VARCHAR AS INCIDENT_KEY,
      PAGE.DOC_ID,
      PAGE.DEDUPE_KEY,
      PAGE.CONTENT_SHA256,
      PAGE.TITLE,
      PAGE.URL,
      PAGE.SOURCE,
      PAGE.DISCOVERED_AT,
      PAGE.MONITOR_STATUS,
      PAGE.PIPELINE_STATE,
      PAGE.RELATIONSHIP_AI_STATUS,
      PAGE.RELATIONSHIP_LABEL,
      PAGE.L2_ROUTE,
      PAGE.EFFECTIVE_ROUTING_REASON AS ROUTING_REASON,
      ARRAY_CONSTRUCT() AS LEAK_TYPE_LABELS,
      NULL::NUMBER AS QUANTITY_CLAIMED,
      NULL::NUMBER AS IMPACT_SEVERITY_SCORE,
      NULL::VARCHAR AS IMPACT_SEVERITY_BAND,
      NULL::NUMBER AS EVIDENCE_CONFIDENCE_SCORE,
      NULL::VARCHAR AS EVIDENCE_CONFIDENCE_BAND,
      NULL::NUMBER AS TRIAGE_PRIORITY_SCORE,
      NULL::VARCHAR AS TRIAGE_PRIORITY_BAND,
      NULL::VARCHAR AS ACTOR_NODE_KEY,
      NULL::VARCHAR AS ACTOR_NAME,
      NULL::NUMBER AS ACTOR_CREDIBILITY_SCORE,
      NULL::VARCHAR AS GROUNDING_LEVEL,
      'new' AS REMEDIATION_STATUS,
      FALSE AS DETAIL_AVAILABLE
    FROM CLASSIFIED_PAGES AS PAGE
    WHERE PAGE.L2_ROUTE = 'target_confirmed'
      AND NOT EXISTS (
        SELECT 1
        FROM NOCTURNE.DASHBOARD.VW_INCIDENTS AS INCIDENT
        WHERE INCIDENT.ORG_ID = PAGE.ORG_ID
          AND INCIDENT.CONTENT_SHA256 = PAGE.CONTENT_SHA256
      )
    QUALIFY ROW_NUMBER() OVER (
      PARTITION BY PAGE.ORG_ID, PAGE.CONTENT_SHA256
      ORDER BY PAGE.DISCOVERED_AT DESC, PAGE.DOC_ID
    ) = 1
  ),
  AUDIT_PAGES AS (
    SELECT
      PAGE.ORG_ID,
      PAGE.ORGANIZATION_NAME,
      PAGE.ORGANIZATION_DOMAIN,
      SHA2(PAGE.ORG_ID || '|audit_page|' || PAGE.DEDUPE_KEY)
        AS MONITOR_KEY,
      NULL::VARCHAR AS INCIDENT_KEY,
      PAGE.DOC_ID,
      PAGE.DEDUPE_KEY,
      PAGE.CONTENT_SHA256,
      PAGE.TITLE,
      PAGE.URL,
      PAGE.SOURCE,
      PAGE.DISCOVERED_AT,
      PAGE.MONITOR_STATUS,
      PAGE.PIPELINE_STATE,
      PAGE.RELATIONSHIP_AI_STATUS,
      PAGE.RELATIONSHIP_LABEL,
      PAGE.L2_ROUTE,
      PAGE.EFFECTIVE_ROUTING_REASON AS ROUTING_REASON,
      ARRAY_CONSTRUCT() AS LEAK_TYPE_LABELS,
      NULL::NUMBER AS QUANTITY_CLAIMED,
      NULL::NUMBER AS IMPACT_SEVERITY_SCORE,
      NULL::VARCHAR AS IMPACT_SEVERITY_BAND,
      NULL::NUMBER AS EVIDENCE_CONFIDENCE_SCORE,
      NULL::VARCHAR AS EVIDENCE_CONFIDENCE_BAND,
      NULL::NUMBER AS TRIAGE_PRIORITY_SCORE,
      NULL::VARCHAR AS TRIAGE_PRIORITY_BAND,
      NULL::VARCHAR AS ACTOR_NODE_KEY,
      NULL::VARCHAR AS ACTOR_NAME,
      NULL::NUMBER AS ACTOR_CREDIBILITY_SCORE,
      NULL::VARCHAR AS GROUNDING_LEVEL,
      IFF(
        PAGE.MONITOR_STATUS = 'another_company',
        'context_only',
        'suppressed'
      ) AS REMEDIATION_STATUS,
      FALSE AS DETAIL_AVAILABLE
    FROM CLASSIFIED_PAGES AS PAGE
    WHERE COALESCE(PAGE.L2_ROUTE, '') <> 'target_confirmed'
  )
  SELECT * FROM CONFIRMED_INCIDENTS
  UNION ALL
  SELECT * FROM PENDING_CONFIRMED
  UNION ALL
  SELECT * FROM AUDIT_PAGES;

-- One row per enabled organization. Counts deliberately describe the complete
-- processing funnel, not only work still waiting in a candidate table.
CREATE OR REPLACE VIEW NOCTURNE.DASHBOARD.VW_COMMAND_CENTER AS
  WITH RAW_COUNTS AS (
    SELECT
      ORG_ID,
      COUNT(*) AS PAGES_COLLECTED,
      MAX(_INGESTED_AT) AS LAST_INGESTED_AT
    FROM NOCTURNE.RAW.CRAWL_PAGES
    WHERE SCHEMA_VERSION = 2
      AND ORG_ID = _PATH_ORG_ID
    GROUP BY ORG_ID
  ),
  L0_COUNTS AS (
    SELECT
      ORG_ID,
      COUNT(*) AS PAGES_SCREENED,
      COUNT(DISTINCT DEDUPE_KEY) AS UNIQUE_PAGES
    FROM NOCTURNE.RAW.DT_REGEX_INDICATORS
    GROUP BY ORG_ID
  ),
  L1_COUNTS AS (
    SELECT
      ORG_ID,
      COUNT(*) AS PAGES_RELEVANCE_CHECKED,
      COUNT_IF(
        RELATIONSHIP_AI_STATUS = 'success'
        AND (
          RELATIONSHIP_LABEL = 'target_data_leak'
          OR (
            RELATIONSHIP_LABEL = 'target_mentioned_no_leak'
            AND COALESCE(TARGET_MATCH_SCORE, 0) > 0
            AND (
              COALESCE(LEAK_MATCHES_SCANNED, 0) > 0
              OR COALESCE(STRONG_INDICATOR_COUNT, 0) > 0
              OR COALESCE(MEDIUM_INDICATOR_COUNT, 0) > 0
            )
          )
        )
      ) AS PAGES_SELECTED_FOR_L2,
      MAX(RELATIONSHIP_CALLED_AT) AS LAST_RELATIONSHIP_AT
    FROM NOCTURNE.RAW.DT_PAGE_RELATIONSHIP_CLASSIFICATION
    GROUP BY ORG_ID
  ),
  L2_COUNTS AS (
    SELECT
      ORG_ID,
      COUNT_IF(STATUS = 'success') AS PAGES_EVIDENCE_EXTRACTED,
      COUNT_IF(STATUS <> 'success') AS L2_EXTRACTION_ERRORS,
      MAX(CALLED_AT) AS LAST_L2_AT
    FROM NOCTURNE.RAW.L2_EXTRACTION_AI_RESULTS
    GROUP BY ORG_ID
  ),
  ROUTING_COUNTS AS (
    SELECT
      ORG_ID,
      COUNT_IF(L2_ROUTE = 'target_confirmed') AS PAGES_OWNERSHIP_VERIFIED
    FROM NOCTURNE.RAW.DT_L2_ROUTING
    GROUP BY ORG_ID
  ),
  LEAK_TYPE_COUNTS AS (
    SELECT
      ORG_ID,
      COUNT_IF(STATUS = 'success') AS PAGES_DATA_TYPES_CLASSIFIED,
      COUNT_IF(STATUS <> 'success') AS LEAK_TYPE_ERRORS,
      MAX(CALLED_AT) AS LAST_LEAK_TYPE_AT
    FROM NOCTURNE.RAW.LEAK_TYPE_AI_RESULTS
    GROUP BY ORG_ID
  ),
  GROUNDING_COUNTS AS (
    SELECT
      ORG_ID,
      COUNT_IF(IS_ACCEPTED AND GROUNDING_LEVEL = 'exact')
        AS EXACT_GROUNDED_COUNT,
      COUNT_IF(IS_ACCEPTED AND GROUNDING_LEVEL = 'normalized')
        AS NORMALIZED_GROUNDED_COUNT,
      COUNT_IF(NOT IS_ACCEPTED OR NOT IS_GROUNDED) AS QUARANTINED_COUNT,
      COUNT(*) AS TOTAL_EXTRACTED_CLAIMS
    FROM NOCTURNE.RAW.DT_L2_CLAIMS
    GROUP BY ORG_ID
  ),
  INCIDENT_COUNTS AS (
    SELECT
      ORG_ID,
      COUNT(*) AS INCIDENTS_RAISED,
      MAX(IMPACT_SEVERITY_SCORE) AS TOP_IMPACT_SEVERITY_SCORE,
      MAX_BY(IMPACT_SEVERITY_BAND, IMPACT_SEVERITY_SCORE)
        AS TOP_IMPACT_SEVERITY_BAND,
      COUNT_IF(IMPACT_SEVERITY_BAND = 'critical') AS CRITICAL_INCIDENTS,
      COUNT_IF(IMPACT_SEVERITY_BAND = 'high') AS HIGH_INCIDENTS,
      COUNT_IF(IMPACT_SEVERITY_BAND = 'medium') AS MEDIUM_INCIDENTS,
      COUNT_IF(IMPACT_SEVERITY_BAND = 'low') AS LOW_INCIDENTS,
      COUNT_IF(IMPACT_SEVERITY_BAND = 'informational')
        AS INFORMATIONAL_INCIDENTS,
      COUNT(DISTINCT ACTOR_NODE_KEY) AS DISTINCT_THREAT_ACTORS,
      MAX(LAST_SEEN) AS LAST_INCIDENT_AT
    FROM NOCTURNE.DASHBOARD.VW_INCIDENTS
    GROUP BY ORG_ID
  )
  SELECT
    ORGANIZATION.ORG_ID,
    ORGANIZATION.CANONICAL_NAME AS ORGANIZATION_NAME,
    ORGANIZATION.ENABLED,
    COALESCE(RAW.PAGES_COLLECTED, 0) AS PAGES_COLLECTED,
    COALESCE(L0.PAGES_SCREENED, 0) AS PAGES_SCREENED,
    COALESCE(L0.UNIQUE_PAGES, 0) AS UNIQUE_PAGES,
    COALESCE(L1.PAGES_RELEVANCE_CHECKED, 0) AS PAGES_RELEVANCE_CHECKED,
    COALESCE(L1.PAGES_SELECTED_FOR_L2, 0) AS PAGES_SELECTED_FOR_L2,
    COALESCE(L2.PAGES_EVIDENCE_EXTRACTED, 0) AS PAGES_EVIDENCE_EXTRACTED,
    COALESCE(ROUTING.PAGES_OWNERSHIP_VERIFIED, 0)
      AS PAGES_OWNERSHIP_VERIFIED,
    COALESCE(LEAK_TYPE.PAGES_DATA_TYPES_CLASSIFIED, 0)
      AS PAGES_DATA_TYPES_CLASSIFIED,
    COALESCE(INCIDENT.INCIDENTS_RAISED, 0) AS INCIDENTS_RAISED,
    INCIDENT.TOP_IMPACT_SEVERITY_SCORE,
    INCIDENT.TOP_IMPACT_SEVERITY_BAND,
    COALESCE(INCIDENT.CRITICAL_INCIDENTS, 0) AS CRITICAL_INCIDENTS,
    COALESCE(INCIDENT.HIGH_INCIDENTS, 0) AS HIGH_INCIDENTS,
    COALESCE(INCIDENT.MEDIUM_INCIDENTS, 0) AS MEDIUM_INCIDENTS,
    COALESCE(INCIDENT.LOW_INCIDENTS, 0) AS LOW_INCIDENTS,
    COALESCE(INCIDENT.INFORMATIONAL_INCIDENTS, 0)
      AS INFORMATIONAL_INCIDENTS,
    COALESCE(INCIDENT.DISTINCT_THREAT_ACTORS, 0)
      AS DISTINCT_THREAT_ACTORS,
    COALESCE(GROUND.EXACT_GROUNDED_COUNT, 0) AS EXACT_GROUNDED_COUNT,
    COALESCE(GROUND.NORMALIZED_GROUNDED_COUNT, 0)
      AS NORMALIZED_GROUNDED_COUNT,
    COALESCE(GROUND.QUARANTINED_COUNT, 0) AS QUARANTINED_COUNT,
    COALESCE(GROUND.TOTAL_EXTRACTED_CLAIMS, 0) AS TOTAL_EXTRACTED_CLAIMS,
    IFF(
      COALESCE(GROUND.TOTAL_EXTRACTED_CLAIMS, 0) = 0,
      0,
      ROUND(
        100 * (
          GROUND.EXACT_GROUNDED_COUNT + GROUND.NORMALIZED_GROUNDED_COUNT
        ) / GROUND.TOTAL_EXTRACTED_CLAIMS,
        1
      )
    ) AS EVIDENCE_GROUNDING_RATE,
    COALESCE(L2.L2_EXTRACTION_ERRORS, 0)
      + COALESCE(LEAK_TYPE.LEAK_TYPE_ERRORS, 0)
        AS DOWNSTREAM_AI_ERROR_COUNT,
    GREATEST_IGNORE_NULLS(
      RAW.LAST_INGESTED_AT,
      L1.LAST_RELATIONSHIP_AT,
      L2.LAST_L2_AT,
      LEAK_TYPE.LAST_LEAK_TYPE_AT,
      INCIDENT.LAST_INCIDENT_AT
    ) AS LAST_UPDATED_AT
  FROM NOCTURNE.CONFIG.MONITORED_ORGANIZATIONS AS ORGANIZATION
  LEFT JOIN RAW_COUNTS AS RAW ON RAW.ORG_ID = ORGANIZATION.ORG_ID
  LEFT JOIN L0_COUNTS AS L0 ON L0.ORG_ID = ORGANIZATION.ORG_ID
  LEFT JOIN L1_COUNTS AS L1 ON L1.ORG_ID = ORGANIZATION.ORG_ID
  LEFT JOIN L2_COUNTS AS L2 ON L2.ORG_ID = ORGANIZATION.ORG_ID
  LEFT JOIN ROUTING_COUNTS AS ROUTING
    ON ROUTING.ORG_ID = ORGANIZATION.ORG_ID
  LEFT JOIN LEAK_TYPE_COUNTS AS LEAK_TYPE
    ON LEAK_TYPE.ORG_ID = ORGANIZATION.ORG_ID
  LEFT JOIN GROUNDING_COUNTS AS GROUND
    ON GROUND.ORG_ID = ORGANIZATION.ORG_ID
  LEFT JOIN INCIDENT_COUNTS AS INCIDENT
    ON INCIDENT.ORG_ID = ORGANIZATION.ORG_ID
  WHERE ORGANIZATION.ENABLED = TRUE;

-- Readiness checks. These return metadata and aggregate counts only.
SELECT TABLE_SCHEMA, TABLE_NAME
FROM NOCTURNE.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'DASHBOARD'
ORDER BY TABLE_NAME;

SELECT
  ORG_ID,
  ORGANIZATION_NAME,
  PAGES_COLLECTED,
  PAGES_RELEVANCE_CHECKED,
  PAGES_EVIDENCE_EXTRACTED,
  PAGES_OWNERSHIP_VERIFIED,
  INCIDENTS_RAISED,
  LAST_UPDATED_AT
FROM NOCTURNE.DASHBOARD.VW_COMMAND_CENTER
ORDER BY ORG_ID;

SELECT
  ORG_ID,
  MONITOR_STATUS,
  COUNT(*) AS MONITOR_ROWS
FROM NOCTURNE.DASHBOARD.VW_BREACH_MONITOR
GROUP BY ORG_ID, MONITOR_STATUS
ORDER BY ORG_ID, MONITOR_STATUS;
