-- =============================================================================
-- Materialized Actor Network Views
-- 
-- These dynamic tables pre-compute the expensive actor network CTE queries
-- that previously ran on every graph page load. They refresh downstream of
-- the knowledge graph tables (12-hour pipeline cycle).
-- =============================================================================

CREATE OR REPLACE DYNAMIC TABLE NOCTURNE.DASHBOARD.DT_ACTOR_NETWORK_NODES
  TARGET_LAG = '12 hours'
  WAREHOUSE = COMPUTE_WH
AS
WITH ACTORS AS (
  SELECT
    ACTOR.ORG_ID,
    ACTOR.ACTOR_NODE_KEY,
    ACTOR.ACTOR_NAME,
    ACTOR.TOTAL_CLAIM_COUNT,
    ACTOR.CORROBORATED_CLAIM_COUNT,
    ACTOR.DOC_COUNT,
    ACTOR.SIGHTING_COUNT,
    ACTOR.MIRROR_SIGHTING_COUNT,
    ACTOR.ACTOR_CREDIBILITY_SCORE,
    ACTOR.FIRST_SEEN,
    ACTOR.LAST_SEEN
  FROM NOCTURNE.DASHBOARD.VW_THREAT_ACTORS AS ACTOR
),
ACTOR_TARGETS AS (
  SELECT DISTINCT
    CLAIM_EDGE.ORG_ID,
    AFFECTS_EDGE.TARGET_KEY AS NODE_KEY
  FROM NOCTURNE.DASHBOARD.VW_KNOWLEDGE_GRAPH_EDGES AS CLAIM_EDGE
  INNER JOIN NOCTURNE.DASHBOARD.VW_KNOWLEDGE_GRAPH_EDGES AS AFFECTS_EDGE
    ON AFFECTS_EDGE.ORG_ID = CLAIM_EDGE.ORG_ID
    AND AFFECTS_EDGE.SOURCE_KEY = CLAIM_EDGE.TARGET_KEY
    AND AFFECTS_EDGE.EDGE_TYPE = 'ALLEGEDLY_AFFECTS'
    AND AFFECTS_EDGE.TARGET_TYPE IN ('organization', 'domain')
  WHERE CLAIM_EDGE.EDGE_TYPE = 'MADE_CLAIM'
    AND CLAIM_EDGE.SOURCE_TYPE = 'actor_alias'
    AND CLAIM_EDGE.TARGET_TYPE = 'claim'

  UNION

  SELECT DISTINCT
    LISTED_EDGE.ORG_ID,
    LISTED_EDGE.TARGET_KEY AS NODE_KEY
  FROM NOCTURNE.DASHBOARD.VW_KNOWLEDGE_GRAPH_EDGES AS LISTED_EDGE
  WHERE LISTED_EDGE.EDGE_TYPE = 'LISTED_ON'
    AND LISTED_EDGE.SOURCE_TYPE = 'actor_alias'
    AND LISTED_EDGE.TARGET_TYPE = 'marketplace'
),
ENTITY_NODES AS (
  SELECT
    NODE.ORG_ID,
    NODE.NODE_KEY,
    NODE.NODE_TYPE,
    NODE.NORMALIZED_NAME,
    NODE.DISPLAY_NAME,
    NODE.NODE_DESCRIPTION,
    NODE.IS_MONITORED_ORG,
    NODE.ENTITY_MATCH_STATUS,
    NODE.ENTITY_MATCH_METHOD,
    NODE.ENTITY_MATCH_CONFIDENCE,
    NODE.MENTION_COUNT,
    NODE.SIGHTING_COUNT,
    NODE.DOC_COUNT,
    NODE.MIRROR_SIGHTING_COUNT,
    NODE.FIRST_SEEN,
    NODE.LAST_SEEN,
    NODE.GRAPH_SCOPE
  FROM NOCTURNE.DASHBOARD.VW_KNOWLEDGE_GRAPH_NODES AS NODE
  INNER JOIN ACTOR_TARGETS AS TARGET
    ON TARGET.ORG_ID = NODE.ORG_ID
    AND TARGET.NODE_KEY = NODE.NODE_KEY
),
ACTOR_NODES AS (
  SELECT
    ORG_ID,
    ACTOR_NODE_KEY AS NODE_KEY,
    'actor_alias' AS NODE_TYPE,
    LOWER(ACTOR_NAME) AS NORMALIZED_NAME,
    ACTOR_NAME AS DISPLAY_NAME,
    'Threat actor aggregate: '
      || TOTAL_CLAIM_COUNT
      || ' claim(s), credibility '
      || ACTOR_CREDIBILITY_SCORE
      || '/100' AS NODE_DESCRIPTION,
    FALSE AS IS_MONITORED_ORG,
    NULL::VARCHAR AS ENTITY_MATCH_STATUS,
    NULL::VARCHAR AS ENTITY_MATCH_METHOD,
    NULL::NUMBER AS ENTITY_MATCH_CONFIDENCE,
    TOTAL_CLAIM_COUNT AS MENTION_COUNT,
    SIGHTING_COUNT,
    DOC_COUNT,
    MIRROR_SIGHTING_COUNT,
    FIRST_SEEN,
    LAST_SEEN,
    'target_incident' AS GRAPH_SCOPE
  FROM ACTORS
),
CLAIM_BUNDLE_NODES AS (
  SELECT
    ORG_ID,
    'actor_claim_bundle:' || ACTOR_NODE_KEY AS NODE_KEY,
    'claim' AS NODE_TYPE,
    LOWER(ACTOR_NAME) || ' claims' AS NORMALIZED_NAME,
    TOTAL_CLAIM_COUNT || ' claim(s)' AS DISPLAY_NAME,
    'Aggregated target-confirmed claims made by ' || ACTOR_NAME AS NODE_DESCRIPTION,
    FALSE AS IS_MONITORED_ORG,
    NULL::VARCHAR AS ENTITY_MATCH_STATUS,
    NULL::VARCHAR AS ENTITY_MATCH_METHOD,
    NULL::NUMBER AS ENTITY_MATCH_CONFIDENCE,
    TOTAL_CLAIM_COUNT AS MENTION_COUNT,
    SIGHTING_COUNT,
    DOC_COUNT,
    MIRROR_SIGHTING_COUNT,
    FIRST_SEEN,
    LAST_SEEN,
    'target_incident' AS GRAPH_SCOPE
  FROM ACTORS
)
SELECT * FROM ACTOR_NODES
UNION ALL
SELECT * FROM CLAIM_BUNDLE_NODES
UNION ALL
SELECT * FROM ENTITY_NODES;


CREATE OR REPLACE DYNAMIC TABLE NOCTURNE.DASHBOARD.DT_ACTOR_NETWORK_EDGES
  TARGET_LAG = '12 hours'
  WAREHOUSE = COMPUTE_WH
AS
WITH ACTORS AS (
  SELECT
    ACTOR.ORG_ID,
    ACTOR.ACTOR_NODE_KEY,
    ACTOR.ACTOR_NAME
  FROM NOCTURNE.DASHBOARD.VW_THREAT_ACTORS AS ACTOR
),
MADE_CLAIM_EDGES AS (
  SELECT
    EDGE.ORG_ID,
    EDGE.SOURCE_KEY,
    EDGE.SOURCE_TYPE,
    EDGE.TARGET_KEY,
    EDGE.TARGET_TYPE,
    EDGE.EDGE_TYPE,
    EDGE.FIRST_SEEN,
    EDGE.LAST_SEEN,
    EDGE.MENTION_COUNT,
    EDGE.SIGHTING_COUNT,
    EDGE.DOC_COUNT,
    EDGE.MIRROR_SIGHTING_COUNT
  FROM NOCTURNE.DASHBOARD.VW_KNOWLEDGE_GRAPH_EDGES AS EDGE
  INNER JOIN ACTORS AS A
    ON A.ORG_ID = EDGE.ORG_ID
    AND A.ACTOR_NODE_KEY = EDGE.SOURCE_KEY
  WHERE EDGE.EDGE_TYPE = 'MADE_CLAIM'
    AND EDGE.SOURCE_TYPE = 'actor_alias'
    AND EDGE.TARGET_TYPE = 'claim'
),
ACTOR_TO_BUNDLE_EDGES AS (
  SELECT
    ORG_ID,
    ACTOR_NODE_KEY AS SOURCE_KEY,
    'actor_alias' AS SOURCE_TYPE,
    'actor_claim_bundle:' || ACTOR_NODE_KEY AS TARGET_KEY,
    'claim' AS TARGET_TYPE,
    'MADE_CLAIM' AS EDGE_TYPE,
    NULL::TIMESTAMP_TZ AS FIRST_SEEN,
    NULL::TIMESTAMP_TZ AS LAST_SEEN,
    NULL::NUMBER AS MENTION_COUNT,
    NULL::NUMBER AS SIGHTING_COUNT,
    NULL::NUMBER AS DOC_COUNT,
    NULL::NUMBER AS MIRROR_SIGHTING_COUNT
  FROM ACTORS
),
BUNDLE_TO_TARGET_EDGES AS (
  SELECT DISTINCT
    AFFECTS_EDGE.ORG_ID,
    'actor_claim_bundle:' || CLAIM_EDGE.SOURCE_KEY AS SOURCE_KEY,
    'claim' AS SOURCE_TYPE,
    AFFECTS_EDGE.TARGET_KEY,
    AFFECTS_EDGE.TARGET_TYPE,
    'ALLEGEDLY_AFFECTS' AS EDGE_TYPE,
    AFFECTS_EDGE.FIRST_SEEN,
    AFFECTS_EDGE.LAST_SEEN,
    AFFECTS_EDGE.MENTION_COUNT,
    AFFECTS_EDGE.SIGHTING_COUNT,
    AFFECTS_EDGE.DOC_COUNT,
    AFFECTS_EDGE.MIRROR_SIGHTING_COUNT
  FROM NOCTURNE.DASHBOARD.VW_KNOWLEDGE_GRAPH_EDGES AS CLAIM_EDGE
  INNER JOIN NOCTURNE.DASHBOARD.VW_KNOWLEDGE_GRAPH_EDGES AS AFFECTS_EDGE
    ON AFFECTS_EDGE.ORG_ID = CLAIM_EDGE.ORG_ID
    AND AFFECTS_EDGE.SOURCE_KEY = CLAIM_EDGE.TARGET_KEY
    AND AFFECTS_EDGE.EDGE_TYPE = 'ALLEGEDLY_AFFECTS'
    AND AFFECTS_EDGE.TARGET_TYPE IN ('organization', 'domain')
  WHERE CLAIM_EDGE.EDGE_TYPE = 'MADE_CLAIM'
    AND CLAIM_EDGE.SOURCE_TYPE = 'actor_alias'
    AND CLAIM_EDGE.TARGET_TYPE = 'claim'
),
LISTED_ON_EDGES AS (
  SELECT
    EDGE.ORG_ID,
    EDGE.SOURCE_KEY,
    EDGE.SOURCE_TYPE,
    EDGE.TARGET_KEY,
    EDGE.TARGET_TYPE,
    EDGE.EDGE_TYPE,
    EDGE.FIRST_SEEN,
    EDGE.LAST_SEEN,
    EDGE.MENTION_COUNT,
    EDGE.SIGHTING_COUNT,
    EDGE.DOC_COUNT,
    EDGE.MIRROR_SIGHTING_COUNT
  FROM NOCTURNE.DASHBOARD.VW_KNOWLEDGE_GRAPH_EDGES AS EDGE
  INNER JOIN ACTORS AS A
    ON A.ORG_ID = EDGE.ORG_ID
    AND A.ACTOR_NODE_KEY = EDGE.SOURCE_KEY
  WHERE EDGE.EDGE_TYPE = 'LISTED_ON'
    AND EDGE.SOURCE_TYPE = 'actor_alias'
    AND EDGE.TARGET_TYPE = 'marketplace'
)
SELECT * FROM ACTOR_TO_BUNDLE_EDGES
UNION ALL
SELECT * FROM BUNDLE_TO_TARGET_EDGES
UNION ALL
SELECT * FROM LISTED_ON_EDGES;
